
# cfdm tutorial notebook

---

## This notebook contains executable code examples from the [cfdm tutorial](https://ncas-cms.github.io/cfdm/tutorial.html).

---
## Contents

* [**CF version**](#CF-version)
* [**Reading datasets**](#Reading-datasets)
* [**Inspection**](#Inspection)
* [**Properties**](#Properties)
* [**Data**](#Data)
* [**Subspacing**](#Subspacing)
* [**Metadata constructs**](#Metadata-constructs)
* [**NetCDF interface**](#NetCDF-interface)
* [**Writing to disk**](#Writing-to-disk)
* [**Field creation**](#Field-creation)
* [**Domain**](#Domain)
* [**Copying**](#Copying)
* [**Equality**](#Equality)
* [**External variables**](#External-variables)

* [**Discrete sampling geometries**](#Discrete-sampling-geometries)
* [**Gathering**](#Gathering)

---
## Before you start

### 0. [Install](https://ncas-cms.github.io/cfdm/installation.html) the cfdm package

### 1. Download the test files

* [**file.nc**](https://github.com/NCAS-CMS/cfdm/raw/master/docs/netcdf_files/file.nc)
* [**parent.nc**](https://github.com/NCAS-CMS/cfdm/raw/master/docs/netcdf_files/parent.nc)
* [**external.nc**](https://github.com/NCAS-CMS/cfdm/raw/master/docs/netcdf_files/external.nc)
* [**contiguous.nc**](https://github.com/NCAS-CMS/cfdm/raw/master/docs/netcdf_files/contiguous.nc)
* [**gathered.nc**](https://github.com/NCAS-CMS/cfdm/raw/master/docs/netcdf_files/gathered.nc)

### 2. Set the local directory which contains the test files

#### By default it is assumed that they are in same directory as this notebook file

In [1]:
DIRECTORY = '.'

### 3. Ensure that  printing works equally well for Python 2 and 3

In [2]:
from __future__ import print_function

---
The cfdm package is imported as follows:
---------------------------------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html)

In [3]:
import cfdm

---
CF version
------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#cf_version)  

In [4]:
cfdm.CF()

'1.7'

---
Reading datasets
------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#reading)

In [5]:
x = cfdm.read(DIRECTORY+'/file.nc')
type(x)

list

---
Inspection
-----------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#inspection)

### Minimal detail

In [6]:
x

[<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>,
 <Field: specific_humidity(latitude(5), longitude(8)) 1>]

In [7]:
(t, q) = x
q

<Field: specific_humidity(latitude(5), longitude(8)) 1>

### Medium detail

In [8]:
print(q)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




In [9]:
print(t)

Field: air_temperature (ncvar%ta)
---------------------------------
Data            : air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K
Cell methods    : grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees) time(1): maximum
Field ancils    : air_temperature standard_error(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K
Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name:Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure%area(grid_longitude(9), grid_latitude(

In [10]:
q.dump()

----------------------------------
Field: specific_humidity (ncvar%q)
----------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'specific_humidity'
units = '1'

Data(latitude(5), longitude(8)) = [[0.007, ..., 0.013]] 1

Cell Method: area: mean

Domain Axis: latitude(5)
Domain Axis: longitude(8)
Domain Axis: time(1)

Dimension coordinate: latitude
    standard_name = 'latitude'
    units = 'degrees_north'
    Data(latitude(5)) = [-75.0, ..., 75.0] degrees_north
    Bounds:Data(latitude(5), 2) = [[-90.0, ..., 90.0]] degrees_north

Dimension coordinate: longitude
    standard_name = 'longitude'
    units = 'degrees_east'
    Data(longitude(8)) = [22.5, ..., 337.5] degrees_east
    Bounds:Data(longitude(8), 2) = [[0.0, ..., 360.0]] degrees_east

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2019-01-01 00:00:00]



In [11]:
t.dump()

---------------------------------
Field: air_temperature (ncvar%ta)
---------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'air_temperature'
units = 'K'

Data(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) = [[[262.8, ..., 269.7]]] K

Cell Method: grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees)
Cell Method: time(1): maximum

Field Ancillary: air_temperature standard_error
    standard_name = 'air_temperature standard_error'
    units = 'K'
    Data(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K

Domain Axis: atmosphere_hybrid_height_coordinate(1)
Domain Axis: grid_latitude(10)
Domain Axis: grid_longitude(9)
Domain Axis: time(1)

Dimension coordinate: atmosphere_hybrid_height_coordinate
    computed_standard_name = 'altitude'
    standard_name = 'atmosphere_hybrid_height_coordinate'
    Data(atmosphere_hybrid_height_coordinate(1)) = [1.5]
    Bounds:Data(atmosphere_hybrid_h

---
Properties
----------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#properties)  

In [12]:
t.properties()

{'Conventions': 'CF-1.7',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

---

In [13]:
t.has_property('standard_name')

True

In [14]:
t.get_property('standard_name')

'air_temperature'

In [15]:
t.del_property('standard_name')

'air_temperature'

In [16]:
t.get_property('standard_name', 'not set')

'not set'

In [17]:
t.set_property('standard_name', 'air_temperature')
t.get_property('standard_name', 'not set')

'air_temperature'

---

In [18]:
original = t.properties({'foo': 'bar', 'units': 'K'})
original

{'project': 'research',
 'units': 'K',
 'standard_name': 'air_temperature',
 'Conventions': 'CF-1.7'}

In [19]:
t.properties()

{'foo': 'bar', 'units': 'K'}

In [20]:
t.properties(original)

{'foo': 'bar', 'units': 'K'}

In [21]:
t.properties()

{'project': 'research',
 'units': 'K',
 'standard_name': 'air_temperature',
 'Conventions': 'CF-1.7'}

---
Data
-----
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#data)

In [22]:
t.get_data()

<Data: [[[262.8, ..., 269.7]]] K>

---

In [23]:
print(t.get_array())

[[[262.8 270.5 279.8 269.5 260.9 265.0 263.5 278.9 269.2]
  [272.7 268.4 279.5 278.9 263.8 263.3 274.2 265.7 279.5]
  [269.7 279.1 273.4 274.2 279.6 270.2 280.0 272.5 263.7]
  [261.7 260.6 270.8 260.3 265.6 279.4 276.9 267.6 260.6]
  [264.2 275.9 262.5 264.9 264.7 270.2 270.4 268.6 275.3]
  [263.9 263.8 272.1 263.7 272.2 264.2 260.0 263.5 270.2]
  [273.8 273.1 268.5 272.3 264.3 278.7 270.6 273.0 270.6]
  [267.9 273.5 279.8 260.3 261.2 275.3 271.2 260.8 268.9]
  [270.9 278.7 273.2 261.7 271.6 265.8 273.0 278.5 266.4]
  [276.4 264.2 276.3 266.1 276.1 268.1 277.0 273.4 269.7]]]


---

In [24]:
t.data.dtype

dtype('float64')

In [25]:
t.data.ndim

3

In [26]:
t.data.shape

(1, 10, 9)

In [27]:
t.data.size

90

### Indexing

In [28]:
data = t.data
data.shape

(1, 10, 9)

In [29]:
data[:, :, 1].shape

(1, 10, 1)

In [30]:
data[:, 0].shape

(1, 1, 9)

In [31]:
data[..., 6:3:-1, 3:6].shape

(1, 3, 3)

In [32]:
data[0, [2, 9], [4, 8]].shape

(1, 2, 2)

In [33]:
data[0, :, -2].shape

(1, 10, 1)

### Assignment

In [34]:
import numpy
t.data[:, :, 1] = -10
t.data[:, 0] = range(9)
t.data[..., 6:3:-1, 3:6] = numpy.arange(-18, -9).reshape(3, 3)
t.data[0, [2, 9], [4, 8]] =  cfdm.Data([[-2, -3]])
t.data[0, :, -2] = numpy.ma.masked
print(t.get_array())

[[[0.0 1.0 2.0 3.0 4.0 5.0 6.0 -- 8.0]
  [272.7 -10.0 279.5 278.9 263.8 263.3 274.2 -- 279.5]
  [269.7 -10.0 273.4 274.2 -2.0 270.2 280.0 -- -3.0]
  [261.7 -10.0 270.8 260.3 265.6 279.4 276.9 -- 260.6]
  [264.2 -10.0 262.5 -12.0 -11.0 -10.0 270.4 -- 275.3]
  [263.9 -10.0 272.1 -15.0 -14.0 -13.0 260.0 -- 270.2]
  [273.8 -10.0 268.5 -18.0 -17.0 -16.0 270.6 -- 270.6]
  [267.9 -10.0 279.8 260.3 261.2 275.3 271.2 -- 268.9]
  [270.9 -10.0 273.2 261.7 271.6 265.8 273.0 -- 266.4]
  [276.4 -10.0 276.3 266.1 -2.0 268.1 277.0 -- -3.0]]]


### Data dimensions

In [35]:
t

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [36]:
t2 = t.squeeze(0)
t2

<Field: air_temperature(grid_latitude(10), grid_longitude(9)) K>

In [37]:
t2 = t2.expand_dims(axis='domainaxis3', position=1)
t2

<Field: air_temperature(grid_latitude(10), time(1), grid_longitude(9)) K>

In [38]:
t2.transpose([2, 0, 1])

<Field: air_temperature(grid_longitude(9), grid_latitude(10), time(1)) K>

---
Subspacing
-------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#subspacing)

In [39]:
print(q)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




In [40]:
new = q[0, ::-1]
print(new)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(1), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(1) = [-75.0] degrees_north
                : longitude(8) = [337.5, ..., 22.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




---
Metadata constructs
---------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#constructs)

In [41]:
q.constructs()

{'cellmethod0': <CellMethod: area: mean>,
 'dimensioncoordinate0': <DimensionCoordinate: latitude(5) degrees_north>,
 'dimensioncoordinate1': <DimensionCoordinate: longitude(8) degrees_east>,
 'dimensioncoordinate2': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainaxis0': <DomainAxis: 5>,
 'domainaxis1': <DomainAxis: 8>,
 'domainaxis2': <DomainAxis: 1>}

In [42]:
t.constructs()

{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
 'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name:Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>,
 'cellmethod0': <CellMethod: domainaxis1: domainaxis2: mean where land (interval: 0.1 degrees)>,
 'cellmethod1': <CellMethod: domainaxis3: maximum>,
 'coordinatereference0': <CoordinateReference: atmosphere_hybrid_height_coordinate>,
 'coordinatereference1': <CoordinateReference: rotated_latitude_longitude>,
 'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainancillary0': <DomainAncillary: ncvar%a(1) m>,
 'domainancillary1': <Doma

---

In [43]:
t.constructs('air_temperature standard_error')

{'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}

In [44]:
t.constructs(construct_type='dimension_coordinate')

{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

In [45]:
t.constructs(axes=['domainaxis1'])

{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
 'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name:Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'domainancillary2': <DomainAncillary: surface_altitude(10, 9) m>,
 'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}

In [46]:
t.constructs(axes=['domainaxis3'])

{'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

In [47]:
t.constructs(construct_type='dimension_coordinate', axes=['domainaxis1'])

{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>}

In [48]:
t.constructs('wavelength')

{}

---

In [49]:
t.constructs(cid='domainancillary2')

{'domainancillary2': <DomainAncillary: surface_altitude(10, 9) m>}

In [50]:
t.constructs('cid%cellmethod1')

{'cellmethod1': <CellMethod: domainaxis3: maximum>}

In [51]:
t.constructs(cid='auxiliarycoordinate999')

{}

---

In [52]:
t.get_construct('latitude')

<AuxiliaryCoordinate: latitude(10, 9) degrees_N>

In [53]:
t.get_construct('units:km2')

<CellMeasure: measure%area(9, 10) km2>

In [54]:
t.constructs('units:degrees')

{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>}

In [55]:
try:
    t.get_construct('units:degrees')
except ValueError:
    print('ValueError: More than one construct meets criteria')

ValueError: More than one construct meets criteria


---

In [56]:
t.cell_methods()

OrderedDict([('cellmethod0',
              <CellMethod: domainaxis1: domainaxis2: mean where land (interval: 0.1 degrees)>),
             ('cellmethod1', <CellMethod: domainaxis3: maximum>)])

In [57]:
t.dimension_coordinates()

{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

### Domain axes

In [58]:
t.construct_axes()

{'auxiliarycoordinate0': ('domainaxis1', 'domainaxis2'),
 'auxiliarycoordinate1': ('domainaxis2', 'domainaxis1'),
 'auxiliarycoordinate2': ('domainaxis1',),
 'cellmeasure0': ('domainaxis2', 'domainaxis1'),
 'dimensioncoordinate0': ('domainaxis0',),
 'dimensioncoordinate1': ('domainaxis1',),
 'dimensioncoordinate2': ('domainaxis2',),
 'dimensioncoordinate3': ('domainaxis3',),
 'domainancillary0': ('domainaxis0',),
 'domainancillary1': ('domainaxis0',),
 'domainancillary2': ('domainaxis1', 'domainaxis2'),
 'fieldancillary0': ('domainaxis1', 'domainaxis2')}

---

In [59]:
t.domain_axes()

{'domainaxis0': <DomainAxis: 1>,
 'domainaxis1': <DomainAxis: 10>,
 'domainaxis2': <DomainAxis: 9>,
 'domainaxis3': <DomainAxis: 1>}

In [60]:
t.get_data_axes()

('domainaxis0', 'domainaxis1', 'domainaxis2')

### Properties and data

In [61]:
lon = q.get_construct('longitude')   
lon

<DimensionCoordinate: longitude(8) degrees_east>

In [62]:
lon.set_property('long_name', 'Longitude')
lon.properties()

{'units': 'degrees_east',
 'long_name': 'Longitude',
 'standard_name': 'longitude'}

In [63]:
lon.data[2]
lon.data[2] = 133.33
print(lon.get_array())

[22.5 67.5 133.33 157.5 202.5 247.5 292.5 337.5]


### Components

In [64]:
lon = t.get_construct('grid_longitude')
bounds = lon.get_bounds()
bounds

<Bounds: grid_longitude(9, 2) >

In [65]:
bounds.properties()

{}

In [66]:
bounds.get_data()
print(bounds.get_array())

[[-4.92 -4.48]
 [-4.48 -4.04]
 [-4.04 -3.6]
 [-3.6 -3.16]
 [-3.16 -2.72]
 [-2.72 -2.28]
 [-2.28 -1.84]
 [-1.84 -1.4]
 [-1.4 -0.96]]


In [67]:
crs = t.get_construct('rotated_latitude_longitude')
crs.datum

<Datum: Parameters: earth_radius>

In [68]:
crs.datum.parameters()

{'earth_radius': 6371007}

In [69]:
crs = t.get_construct('atmosphere_hybrid_height_coordinate',
                          construct_type='coordinate_reference')
crs.coordinate_conversion.domain_ancillaries()

{u'a': 'domainancillary0',
 u'b': 'domainancillary1',
 u'orog': 'domainancillary2'}

---
NetCDF interface
---------------- 
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#netcdf-interface)

In [70]:
q.nc_get_variable()

u'q'

In [71]:
q.nc_global_attributes()

{'Conventions', 'project'}

In [72]:
q.nc_unlimited_dimensions()

set()

In [73]:
q.nc_set_variable('humidity')
q.nc_get_variable()

'humidity'

---

In [74]:
t.constructs('ncvar%b')

{'domainancillary1': <DomainAncillary: ncvar%b(1) >}

In [75]:
t.get_construct('ncvar%x')

<DimensionCoordinate: grid_longitude(9) degrees>

In [76]:
t.get_construct('ncdim%x')

<DomainAxis: 9>

---
Writing to disk
---------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#writing-to-disk)

In [77]:
print(q)

Field: specific_humidity (ncvar%humidity)
-----------------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




In [78]:
cfdm.write(q, 'q_file.nc')

In [79]:
!ncdump -h q_file.nc

netcdf q_file {
dimensions:
	lat = 5 ;
	bounds2 = 2 ;
	lon = 8 ;
variables:
	double lat_bnds(lat, bounds2) ;
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:bounds = "lat_bnds" ;
	double lon_bnds(lon, bounds2) ;
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "Longitude" ;
		lon:standard_name = "longitude" ;
		lon:bounds = "lon_bnds" ;
	double time ;
		time:units = "days since 2018-12-01" ;
		time:standard_name = "time" ;
	double humidity(lat, lon) ;
		humidity:standard_name = "specific_humidity" ;
		humidity:cell_methods = "area: mean" ;
		humidity:units = "1" ;
		humidity:coordinates = "time" ;

// global attributes:
		:Conventions = "CF-1.7" ;
		:project = "research" ;
}


---

In [80]:
x

[<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>,
 <Field: specific_humidity(latitude(5), longitude(8)) 1>]

In [81]:
cfdm.write(x, 'new_file.nc')

### Scalar coordinate variables

In [82]:
q

<Field: specific_humidity(latitude(5), longitude(8)) 1>

q.dimension_coordinates()

In [83]:
q.construct_axes()

{'dimensioncoordinate0': ('domainaxis0',),
 'dimensioncoordinate1': ('domainaxis1',),
 'dimensioncoordinate2': ('domainaxis2',)}

In [84]:
q2 = q.expand_dims(axis='domainaxis2')
q2

<Field: specific_humidity(time(1), latitude(5), longitude(8)) 1>

In [85]:
cfdm.write(q2, 'q2_file.nc')

In [86]:
!ncdump -h q2_file.nc

netcdf q2_file {
dimensions:
	lat = 5 ;
	bounds2 = 2 ;
	lon = 8 ;
	time = 1 ;
variables:
	double lat_bnds(lat, bounds2) ;
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:bounds = "lat_bnds" ;
	double lon_bnds(lon, bounds2) ;
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "Longitude" ;
		lon:standard_name = "longitude" ;
		lon:bounds = "lon_bnds" ;
	double time(time) ;
		time:units = "days since 2018-12-01" ;
		time:standard_name = "time" ;
	double humidity(time, lat, lon) ;
		humidity:units = "1" ;
		humidity:standard_name = "specific_humidity" ;
		humidity:cell_methods = "area: mean" ;

// global attributes:
		:Conventions = "CF-1.7" ;
		:project = "research" ;
}


---
Field creation
----------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#field-creation)

In [87]:
p = cfdm.Field(properties={'standard_name': 'precipitation_flux'})
p

<Field: precipitation_flux>

In [88]:
dc = cfdm.DimensionCoordinate(properties={'long_name': 'Longitude'},
                              data=cfdm.Data([0, 1, 2.]))
dc

<DimensionCoordinate: long_name:Longitude(3) >

In [89]:
fa = cfdm.FieldAncillary(
           properties={'standard_name': 'precipitation_flux status_flag'},
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

<FieldAncillary: precipitation_flux status_flag(3) >

---

In [90]:
p = cfdm.Field()
p

<Field: >

In [91]:
p.set_property('standard_name', 'precipitation_flux')
p

<Field: precipitation_flux>

In [92]:
dc = cfdm.DimensionCoordinate()
dc

<DimensionCoordinate:  >

In [93]:
dc.set_property('long_name', 'Longitude')
dc.set_data(cfdm.Data([1, 2, 3.]))
dc

<DimensionCoordinate: long_name:Longitude(3) >

In [94]:
fa = cfdm.FieldAncillary(
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

<FieldAncillary: (3) >

In [95]:
fa.set_property('standard_name', 'precipitation_flux status_flag')
fa

<FieldAncillary: precipitation_flux status_flag(3) >

---

In [96]:
longitude_axis = p.set_domain_axis(cfdm.DomainAxis(3))
longitude_axis

'domainaxis0'

In [97]:
cid = p.set_dimension_coordinate(dc, axes=[longitude_axis])
cid

'dimensioncoordinate0'

In [98]:
cm = cfdm.CellMethod(axes=[longitude_axis],
                     properties={'method': 'minimum'})
p.set_cell_method(cm)
print(p)

Field: precipitation_flux
-------------------------
Data            : precipitation_flux
Cell methods    : long_name:Longitude(3): minimum
Dimension coords: long_name:Longitude(3) = [1.0, 2.0, 3.0]




---

In [99]:
import numpy
import cfdm

# Initialise the field with properties
Q = cfdm.Field(properties={'project': 'research',
                           'standard_name': 'specific_humidity',
                           'units': '1'})

# Create the domain axes
domain_axisT = cfdm.DomainAxis(1)
domain_axisY = cfdm.DomainAxis(5)
domain_axisX = cfdm.DomainAxis(8)

# Insert the domain axes into the field. The set_domain_axis method
# returns the domain axis construct identifier that will be used
# later to specify which domain axis corresponds to which dimension
# coordinate construct.  
axisT = Q.set_domain_axis(domain_axisT)
axisY = Q.set_domain_axis(domain_axisY)
axisX = Q.set_domain_axis(domain_axisX)

# Field data
data = cfdm.Data(numpy.arange(40.).reshape(5, 8))
Q.set_data(data, axes=[axisY, axisX])

# Create the cell methods
cell_method1 = cfdm.CellMethod(axes=['area'], properties={'method': 'mean'})

cell_method2 = cfdm.CellMethod()
cell_method2.set_axes([axisT])
cell_method2.properties({'method': 'maximum'})

# Insert the cell methods into the field
Q.set_cell_method(cell_method1)
Q.set_cell_method(cell_method2)

# Create the dimension Coordinates
dimT = cfdm.DimensionCoordinate(
         properties={'standard_name': 'time',
                     'units': 'days since 2018-12-01'},
         data=cfdm.Data([15.5]),
         bounds=cfdm.Bounds(data=cfdm.Data([[0,31.]])))

dimY = cfdm.DimensionCoordinate(properties={'standard_name': 'latitude',
                                    'units': 'degrees_north'})
array = numpy.arange(5.)
dimY.set_data(cfdm.Data(array))
bounds_array = numpy.empty((5, 2))
bounds_array[:, 0] = array - 0.5
bounds_array[:, 1] = array + 0.5
bounds = cfdm.Bounds(data=cfdm.Data(bounds_array))
dimY.set_bounds(bounds)

dimX = cfdm.DimensionCoordinate(data=cfdm.Data(numpy.arange(8.)))
dimX.properties({'standard_name': 'longitude',
                 'units': 'degrees_east'})

# Insert the dimension coordinates into the field, specifying to
# which domain axis each one corresponds
Q.set_dimension_coordinate(dimT, axes=[axisT])
Q.set_dimension_coordinate(dimY, axes=[axisY])
Q.set_dimension_coordinate(dimX, axes=[axisX])

'dimensioncoordinate2'

In [100]:
Q.dump()

------------------------
Field: specific_humidity
------------------------
project = 'research'
standard_name = 'specific_humidity'
units = '1'

Data(latitude(5), longitude(8)) = [[0.0, ..., 39.0]] 1

Cell Method: area: mean
Cell Method: time(1): maximum

Domain Axis: latitude(5)
Domain Axis: longitude(8)
Domain Axis: time(1)

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2018-12-16 12:00:00]
    Bounds:Data(time(1), 2) = [[2018-12-01 00:00:00, 2019-01-01 00:00:00]]

Dimension coordinate: latitude
    standard_name = 'latitude'
    units = 'degrees_north'
    Data(latitude(5)) = [0.0, ..., 4.0] degrees_north
    Bounds:Data(latitude(5), 2) = [[-0.5, ..., 4.5]] degrees_north

Dimension coordinate: longitude
    standard_name = 'longitude'
    units = 'degrees_east'
    Data(longitude(8)) = [0.0, ..., 7.0] degrees_east



In [101]:
Q.nc_set_variable('q')

domain_axisT.nc_set_dimension('time')
domain_axisY.nc_set_dimension('lat')
domain_axisX.nc_set_dimension('lon')

dimT.nc_set_variable('time')
dimY.nc_set_variable('lat')
dimX.nc_set_variable('lon')

---

In [102]:
import numpy
import cfdm

# Initialize the field
tas = cfdm.Field(
    properties={'project': 'research',
                'standard_name': 'air_temperature',
                    'units': 'K'})

# Create and set domain axes
axis_T = tas.set_domain_axis(cfdm.DomainAxis(1))
axis_Z = tas.set_domain_axis(cfdm.DomainAxis(1))
axis_Y = tas.set_domain_axis(cfdm.DomainAxis(10))
axis_X = tas.set_domain_axis(cfdm.DomainAxis(9))

# Set the field data
tas.set_data(cfdm.Data(numpy.arange(90.).reshape(10, 9)),
             axes=[axis_Y, axis_X])

# Create and set the cell methods
cell_method1 = cfdm.CellMethod(
          axes=[axis_Y, axis_X],
          properties={'method': 'mean',
                      'where': 'land',
              'intervals': [cfdm.Data(0.1, units='degrees')]})

cell_method2 = cfdm.CellMethod(
                 axes=[axis_T],
             properties={'method': 'maximum'})

tas.set_cell_method(cell_method1)
tas.set_cell_method(cell_method2)

# Create and set the field ancillaries
field_ancillary = cfdm.FieldAncillary(
             properties={'standard_name': 'air_temperature standard_error',
                          'units': 'K'},
             data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

tas.set_field_ancillary(field_ancillary, axes=[axis_Y, axis_X])

# Create and set the dimension coordinates
dimension_coordinate_T = cfdm.DimensionCoordinate(
                           properties={'standard_name': 'time',
                                       'units': 'days since 2018-12-01'},
                       data=cfdm.Data([15.5]),
                       bounds=cfdm.Bounds(data=cfdm.Data([[0., 31]])))

dimension_coordinate_Z = cfdm.DimensionCoordinate(
    properties={'computed_standard_name': 'altitude',
                    'standard_name': 'atmosphere_hybrid_height_coordinate'},
        data = cfdm.Data([1.5]),
        bounds=cfdm.Bounds(data=cfdm.Data([[1.0, 2.0]])))

dimension_coordinate_Y = cfdm.DimensionCoordinate(
    properties={'standard_name': 'grid_latitude',
                 'units': 'degrees'},
    data=cfdm.Data(numpy.arange(10.)),
        bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(20).reshape(10, 2))))

dimension_coordinate_X = cfdm.DimensionCoordinate(
        properties={'standard_name': 'grid_longitude',
                    'units': 'degrees'},
    data=cfdm.Data(numpy.arange(9.)),
    bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(18).reshape(9, 2))))

tas.set_dimension_coordinate(dimension_coordinate_T, axes=[axis_T])
tas.set_dimension_coordinate(dimension_coordinate_Z, axes=[axis_Z])
tas.set_dimension_coordinate(dimension_coordinate_Y, axes=[axis_Y])
tas.set_dimension_coordinate(dimension_coordinate_X, axes=[axis_X])

# Create and set the auxiliary coordinates
auxiliary_coordinate_lat = cfdm.AuxiliaryCoordinate(
                      properties={'standard_name': 'latitude',
                                  'units': 'degrees_north'},
                      data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

auxiliary_coordinate_lon = cfdm.AuxiliaryCoordinate(
                      properties={'standard_name': 'longitude',
                          'units': 'degrees_east'},
                  data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

array = numpy.ma.array(list('abcdefghij'))
array[0] = numpy.ma.masked
auxiliary_coordinate_name = cfdm.AuxiliaryCoordinate(
                       properties={'long_name': 'Grid latitude name'},
                       data=cfdm.Data(array))

tas.set_auxiliary_coordinate(auxiliary_coordinate_lat,
                         axes=[axis_Y, axis_X])
tas.set_auxiliary_coordinate(auxiliary_coordinate_lon,
                         axes=[axis_X, axis_Y])
tas.set_auxiliary_coordinate(auxiliary_coordinate_name, axes=[axis_Y])

# Create and set domain ancillaries
domain_ancillary_a = cfdm.DomainAncillary(
                   properties={'units': 'm'},
                   data=cfdm.Data([10.]),
                       bounds=cfdm.Bounds(data=cfdm.Data([[5., 15.]])))

domain_ancillary_b = cfdm.DomainAncillary(
                   properties={'units': '1'},
                       data=cfdm.Data([20.]),
                   bounds=cfdm.Bounds(data=cfdm.Data([[14, 26.]])))

domain_ancillary_orog = cfdm.DomainAncillary(
                          properties={'standard_name': 'surface_altitude',
                                       'units': 'm'},
                      data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

tas.set_domain_ancillary(domain_ancillary_a, axes=[axis_Z])
tas.set_domain_ancillary(domain_ancillary_b, axes=[axis_Z])
tas.set_domain_ancillary(domain_ancillary_orog, axes=[axis_Y, axis_X])

# Create and set the coordinate references
datum = cfdm.Datum(parameters={'earth_radius': 6371007.})

coordinate_conversion_h = cfdm.CoordinateConversion(
              parameters={'grid_mapping_name': 'rotated_latitude_longitude',
                          'grid_north_pole_latitude': 38.0,
                          'grid_north_pole_longitude': 190.0})

horizontal_crs = cfdm.CoordinateReference(
                   datum=datum,
                   coordinate_conversion=coordinate_conversion_h,
               coordinates=[dimension_coordinate_X,
                                dimension_coordinate_Y,
                                auxiliary_coordinate_lat,
                auxiliary_coordinate_lon])

coordinate_conversion_v = cfdm.CoordinateConversion(
         parameters={'standard_name': 'atmosphere_hybrid_height_coordinate',
                     'computed_standard_name': 'altitude'},
         domain_ancillaries={'a': domain_ancillary_a,
                             'b': domain_ancillary_a,
                             'orog': domain_ancillary_orog})

vertical_crs = cfdm.CoordinateReference(
                 datum=datum,
                 coordinate_conversion=coordinate_conversion_v,
             coordinates=[dimension_coordinate_Z])

tas.set_coordinate_reference(horizontal_crs)
tas.set_coordinate_reference(vertical_crs)

# Create and set the cell measures
cell_measure = cfdm.CellMeasure(measure='area',
                 properties={'units': 'km2'},
                 data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

tas.set_cell_measure(cell_measure, axes=[axis_X, axis_Y])

'cellmeasure0'

In [103]:
print(tas)

Field: air_temperature
----------------------
Data            : air_temperature(grid_latitude(10), grid_longitude(9)) K
Cell methods    : grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees) time(1): maximum
Field ancils    : air_temperature standard_error(grid_latitude(10), grid_longitude(9)) = [[0.0, ..., 89.0]] K
Dimension coords: time(1) = [2018-12-16 12:00:00]
                : atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [0.0, ..., 9.0] degrees
                : grid_longitude(9) = [0.0, ..., 8.0] degrees
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[0.0, ..., 89.0]] degrees_north
                : longitude(grid_longitude(9), grid_latitude(10)) = [[0.0, ..., 89.0]] degrees_east
                : long_name:Grid latitude name(grid_latitude(10)) = [--, ..., j]
Cell measures   : measure%area(grid_longitude(9), grid_latitude(10)) = [[0.0, ..., 89.0]] km2
Coord references: atmosphere_hybrid_height_

---
Domain
-------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#domain)

In [104]:
domain = t.get_domain()
domain

<Domain: {1, 1, 9, 10}>

In [105]:
print(domain)

Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name:Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure%area(grid_longitude(9), grid_latitude(10)) = [[2391.9657, ..., 2392.6009]] km2
Coord references: atmosphere_hybrid_height_coordinate
                : rotated_latitude_longitude
Domain ancils   : ncvar%a(atmosphere_hybrid_height_coordinate(1)) = [10.0] m
                : ncvar%b(atmosphere_hybrid_height_coordinate(1)) = [20.0]
                : surface_altitude(grid_latitude(10), grid_longitude(9)) = [[0.0, ..., 270.0]] m



In [106]:
domain.dump()

Domain Axis: atmosphere_hybrid_height_coordinate(1)
Domain Axis: grid_latitude(10)
Domain Axis: grid_longitude(9)
Domain Axis: time(1)

Dimension coordinate: atmosphere_hybrid_height_coordinate
    computed_standard_name = 'altitude'
    standard_name = 'atmosphere_hybrid_height_coordinate'
    Data(atmosphere_hybrid_height_coordinate(1)) = [1.5]
    Bounds:Data(atmosphere_hybrid_height_coordinate(1), 2) = [[1.0, 2.0]]

Dimension coordinate: grid_latitude
    standard_name = 'grid_latitude'
    units = 'degrees'
    Data(grid_latitude(10)) = [2.2, ..., -1.76] degrees
    Bounds:Data(grid_latitude(10), 2) = [[2.42, ..., -1.98]] degrees

Dimension coordinate: grid_longitude
    standard_name = 'grid_longitude'
    units = 'degrees'
    Data(grid_longitude(9)) = [-4.7, ..., -1.18] degrees
    Bounds:Data(grid_longitude(9), 2) = [[-4.92, ..., -0.96]] degrees

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2019-01-01 00:00:00]


In [107]:
domain.get_construct('latitude').set_property('test', 'set by domain')

In [108]:
t.get_construct('latitude').get_property('test')

'set by domain'

In [109]:
t.get_construct('latitude').set_property('test', 'set by field')

In [110]:
domain.get_construct('latitude').get_property('test')

'set by field'

In [111]:
domain.get_construct('latitude').del_property('test')

'set by field'

In [112]:
t.get_construct('latitude').has_property('test')

False

---
Copying
--------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#copying)

In [113]:
t

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [114]:
u = t.copy()
u

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [115]:
u.del_construct('grid_latitude')

<DimensionCoordinate: grid_latitude(10) degrees>

In [116]:
u.constructs('grid_latitude')

{}

In [117]:
t.constructs('grid_latitude')

{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>}

---

In [118]:
import copy
u = copy.deepcopy(t)

---

In [119]:
orog = t.get_construct('surface_altitude').copy()
orog

<DomainAncillary: surface_altitude(10, 9) m>

---
Equality
-----------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#equality)

In [120]:
t.equals(t)

True

In [121]:
t.equals(t.copy())

True

In [122]:
t.equals(q)

False

In [123]:
t.equals(q, traceback=True)

Field: Different units: 'K', '1'
Field: Different properties


False

---

In [124]:
cfdm.ATOL()

2.220446049250313e-16

In [125]:
cfdm.RTOL()

2.220446049250313e-16

In [126]:
original = cfdm.RTOL(0.00001)
cfdm.RTOL()

1e-05

In [127]:
cfdm.RTOL(original)

1e-05

In [128]:
cfdm.RTOL()

2.220446049250313e-16

---
External variables
-----------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#external-variables)

In [129]:
!ncdump -h parent.nc

netcdf parent {
dimensions:
	latitude = 10 ;
	longitude = 9 ;
variables:
	double latitude(latitude) ;
		latitude:units = "degrees_north" ;
		latitude:standard_name = "latitude" ;
	double longitude(longitude) ;
		longitude:units = "degrees_east" ;
		longitude:standard_name = "longitude" ;
	double eastward_wind(latitude, longitude) ;
		eastward_wind:units = "m s-1" ;
		eastward_wind:standard_name = "eastward_wind" ;
		eastward_wind:cell_measures = "area: areacella" ;

// global attributes:
		:Conventions = "1.7" ;
		:external_variables = "areacella" ;
}


In [130]:
!ncdump -h external.nc 

netcdf external {
dimensions:
	latitude = 10 ;
	longitude = 9 ;
variables:
	double areacella(longitude, latitude) ;
		areacella:units = "m2" ;
		areacella:standard_name = "cell_area" ;

// global attributes:
		:Conventions = "1.7" ;
}


In [131]:
u = cfdm.read(DIRECTORY+'/parent.nc')[0]
print(u)

Field: eastward_wind (ncvar%eastward_wind)
------------------------------------------
Data            : eastward_wind(latitude(10), longitude(9)) m s-1
Dimension coords: latitude(10) = [0.0, ..., 9.0] degrees_north
                : longitude(9) = [0.0, ..., 8.0] degrees_east
Cell measures   : measure%area (external variable: ncvar%areacella)




In [132]:
area = u.get_construct('measure%area')
area

<CellMeasure: measure%area >

In [133]:
area.nc_external()

True

In [134]:
area.nc_get_variable()

u'areacella'

In [135]:
area.properties()

{}

In [136]:
area.has_data()

False

---

In [137]:
g = cfdm.read(DIRECTORY+'/parent.nc', external_files=DIRECTORY+'/external.nc')[0]
print(g)

Field: eastward_wind (ncvar%eastward_wind)
------------------------------------------
Data            : eastward_wind(latitude(10), longitude(9)) m s-1
Dimension coords: latitude(10) = [0.0, ..., 9.0] degrees_north
                : longitude(9) = [0.0, ..., 8.0] degrees_east
Cell measures   : cell_area(longitude(9), latitude(10)) = [[100000.5, ..., 100089.5]] m2




In [138]:
area = g.get_construct('cell_area')
area

<CellMeasure: cell_area(9, 10) m2>

In [139]:
area.nc_external()

False

In [140]:
area.nc_get_variable()

u'areacella'

In [141]:
area.properties()

{'standard_name': 'cell_area', 'units': 'm2'}

In [142]:
area.get_data()

<Data: [[100000.5, ..., 100089.5]] m2>

---

In [143]:
area.nc_external(True)

False

In [144]:
cfdm.write(g, 'new_parent.nc', external_file='new_external.nc')

---
Discrete sampling geometries
------------------------------------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#discrete-sampling-geometries)

In [145]:
!ncdump -h contiguous.nc

netcdf contiguous {
dimensions:
	station = 4 ;
	obs = 24 ;
	strlen8 = 8 ;
variables:
	int row_size(station) ;
		row_size:long_name = "number of observations for this station" ;
		row_size:sample_dimension = "obs" ;
	double time(obs) ;
		time:units = "days since 1970-01-01 00:00:00" ;
		time:standard_name = "time" ;
	double lat(station) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
	double lon(station) ;
		lon:units = "degrees_east" ;
		lon:standard_name = "longitude" ;
	double alt(station) ;
		alt:units = "m" ;
		alt:positive = "up" ;
		alt:standard_name = "height" ;
		alt:axis = "Z" ;
	char station_name(station, strlen8) ;
		station_name:long_name = "station name" ;
		station_name:cf_role = "timeseries_id" ;
	double humidity(obs) ;
		humidity:standard_name = "specific_humidity" ;
		humidity:coordinates = "time lat lon alt station_name" ;
		humidity:_FillValue = -999.9 ;

// global attributes:
		:Conventions = "CF-1.7" ;
		:featureType = "timeSeries" ;
}


---

In [146]:
h = cfdm.read(DIRECTORY+'/contiguous.nc')[0]
print(h)

Field: specific_humidity (ncvar%humidity)
-----------------------------------------
Data            : specific_humidity(ncdim%station(4), ncdim%timeseries(9))
Auxiliary coords: time(ncdim%station(4), ncdim%timeseries(9)) = [[1969-12-29 00:00:00, ..., 1970-01-07 00:00:00]]
                : latitude(ncdim%station(4)) = [-9.0, ..., 78.0] degrees_north
                : longitude(ncdim%station(4)) = [-23.0, ..., 178.0] degrees_east
                : height(ncdim%station(4)) = [0.5, ..., 345.0] m
                : cf_role:timeseries_id(ncdim%station(4)) = [station1, ..., station4]




In [147]:
print(h.get_array())

[[0.12 0.05 0.18 -- -- -- -- -- --]
 [0.05 0.11 0.2 0.15 0.08 0.04 0.06 -- --]
 [0.15 0.19 0.15 0.17 0.07 -- -- -- --]
 [0.11 0.03 0.14 0.16 0.02 0.09 0.1 0.04 0.11]]


In [148]:
h.data.get_compression_type()

'ragged contiguous'

In [149]:
print(h.data.get_compressed_array())

[0.12 0.05 0.18 0.05 0.11 0.2 0.15 0.08 0.04 0.06 0.15 0.19 0.15 0.17 0.07
 0.11 0.03 0.14 0.16 0.02 0.09 0.1 0.04 0.11]


In [150]:
count_variable = h.data.get_count_variable()
count_variable

<Count: long_name:number of observations for this station(4) >

In [151]:
print(count_variable.get_array())

[3 7 5 9]


---

In [152]:
station = h[1]
station

<Field: specific_humidity(ncdim%station(1), ncdim%timeseries(9))>

In [153]:
print(station.get_array())

[[0.05 0.11 0.2 0.15 0.08 0.04 0.06 -- --]]


---

In [154]:
h.data.get_compression_type()

'ragged contiguous'

In [155]:
h.data[1, 2] = -9
print(h.get_array())

[[0.12 0.05 0.18 -- -- -- -- -- --]
 [0.05 0.11 -9.0 0.15 0.08 0.04 0.06 -- --]
 [0.15 0.19 0.15 0.17 0.07 -- -- -- --]
 [0.11 0.03 0.14 0.16 0.02 0.09 0.1 0.04 0.11]]


In [156]:
h.data.get_compression_type()

''

---

In [157]:
import numpy
import cfdm

# Define the ragged array values
ragged_array = numpy.array([280, 282.5, 281, 279, 278, 279.5],
                           dtype='float32')

# Define the count array values
count_array = [2, 4]

# Create the count variable
count_variable = cfdm.Count(data=cfdm.Data(count_array))
count_variable.set_property('long_name', 'number of obs for this timeseries')

# Create the contiguous ragged array object
array = cfdm.RaggedContiguousArray(
                 compressed_array=cfdm.NumpyArray(ragged_array),
                 shape=(2, 4), size=8, ndim=2,
                 count_variable=count_variable)

# Create the field construct with the domain axes and the ragged
# array
tas = cfdm.Field()
tas.properties({'standard_name': 'air_temperature',
                'units': 'K'})

# Create the domain axis constructs for the uncompressed array
X = tas.set_domain_axis(cfdm.DomainAxis(4))
Y = tas.set_domain_axis(cfdm.DomainAxis(2))

# Set the data for the field
tas.set_data(cfdm.Data(array), axes=[Y, X])

---

In [158]:
tas

<Field: air_temperature(cid%domainaxis1(2), cid%domainaxis0(4)) K>

In [159]:
print(tas.get_array())

[[280.0 282.5 -- --]
 [281.0 279.0 278.0 279.5]]


In [160]:
tas.data.get_compression_type()

'ragged contiguous'

In [161]:
print(tas.data.get_compressed_array())

[ 280.   282.5  281.   279.   278.   279.5]


In [162]:
count_variable = tas.data.get_count_variable()
count_variable

<Count: long_name:number of obs for this timeseries(2) >

In [163]:
print(count_variable.get_array())

[2 4]


In [164]:
cfdm.write(tas, 'tas_contiguous.nc')

In [165]:
!ncdump tas_contiguous.nc

netcdf tas_contiguous {
dimensions:
	dim = 2 ;
	element = 6 ;
variables:
	int64 count(dim) ;
		count:long_name = "number of obs for this timeseries" ;
		count:sample_dimension = "element" ;
	float air_temperature(element) ;
		air_temperature:units = "K" ;
		air_temperature:standard_name = "air_temperature" ;

// global attributes:
		:Conventions = "CF-1.7" ;
data:

 count = 2, 4 ;

 air_temperature = 280, 282.5, 281, 279, 278, 279.5 ;
}


---
Gathering
----------
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#gathering)

In [166]:
p = cfdm.read(DIRECTORY+'/gathered.nc')[0]
print(p)

Field: precipitation_flux (ncvar%pr)
------------------------------------
Data            : precipitation_flux(time(2), latitude(4), longitude(5)) kg m2 s-1
Dimension coords: time(2) = [2000-02-01 00:00:00, 2000-03-01 00:00:00]
                : latitude(4) = [-90.0, ..., -75.0] degrees_north
                : longitude(5) = [0.0, ..., 40.0] degrees_east




In [167]:
print(p.get_array())

[[[-- 0.000122 0.0008 -- --]
  [0.000177 -- 0.000175 0.00058 --]
  [-- -- -- -- --]
  [-- 0.000206 -- 0.0007 --]]

 [[-- 0.000202 0.000174 -- --]
  [0.00084 -- 0.000201 0.0057 --]
  [-- -- -- -- --]
  [-- 0.000223 -- 0.000102 --]]]


In [168]:
p.data.get_compression_type()

'gathered'

In [169]:
print(p.data.get_compressed_array())

[[0.000122 0.0008 0.000177 0.000175 0.00058 0.000206 0.0007]
 [0.000202 0.000174 0.00084 0.000201 0.0057 0.000223 0.000102]]


In [170]:
list_variable = p.data.get_list_variable()
list_variable

<List: ncvar%landpoint(7) >

In [171]:
print(list_variable.get_array())

[1 2 5 7 8 16 18]


---

In [172]:
p[0]

<Field: precipitation_flux(time(1), latitude(4), longitude(5)) kg m2 s-1>

In [173]:
p[1, :, 3:5]

<Field: precipitation_flux(time(1), latitude(4), longitude(2)) kg m2 s-1>

---

In [174]:
p.data.get_compression_type()

'gathered'

In [175]:
p.data[1] = -9

In [176]:
p.data.get_compression_type()

''

---

In [177]:
import numpy   
import cfdm

# Define the gathered values
gathered_array = numpy.array([[280, 282.5, 281], [279, 278, 277.5]],
                             dtype='float32')

# Define the list array values
list_array = [1, 4, 5]

# Create the list variable
list_variable = cfdm.List(data=cfdm.Data(list_array))

# Create the gathered array object
array = cfdm.GatheredArray(
                 compressed_array=cfdm.NumpyArray(gathered_array),
         compressed_dimension=1,
                 shape=(2, 3, 2), size=12, ndim=3,
                 list_variable=list_variable)

# Create the field construct with the domain axes and the gathered
# array
tas = cfdm.Field(properties={'standard_name': 'air_temperature',
                             'units': 'K'})

# Create the domain axis constructs for the uncompressed array
T = tas.set_domain_axis(cfdm.DomainAxis(2))
Y = tas.set_domain_axis(cfdm.DomainAxis(3))
X = tas.set_domain_axis(cfdm.DomainAxis(2))

# Set the data for the field
tas.set_data(cfdm.Data(array), axes=[T, Y, X])                 

---

In [178]:
tas

<Field: air_temperature(cid%domainaxis0(2), cid%domainaxis1(3), cid%domainaxis2(2)) K>

In [179]:
print(tas.get_array())

[[[-- 280.0]
  [-- --]
  [282.5 281.0]]

 [[-- 279.0]
  [-- --]
  [278.0 277.5]]]


In [180]:
tas.data.get_compression_type()

'gathered'

In [181]:
print(tas.data.get_compressed_array())

[[ 280.   282.5  281. ]
 [ 279.   278.   277.5]]


In [182]:
list_variable = tas.data.get_list_variable()
list_variable 

<List: (3) >

In [183]:
print(list_variable.get_array())

[1 4 5]


In [184]:
cfdm.write(tas, 'tas_gathered.nc')

In [185]:
!ncdump tas_gathered.nc

netcdf tas_gathered {
dimensions:
	dim = 2 ;
	dim_1 = 3 ;
	dim_2 = 2 ;
	list = 3 ;
variables:
	int64 list(list) ;
		list:compress = "dim_1 dim_2" ;
	float air_temperature(dim, list) ;
		air_temperature:units = "K" ;
		air_temperature:standard_name = "air_temperature" ;

// global attributes:
		:Conventions = "CF-1.7" ;
data:

 list = 1, 4, 5 ;

 air_temperature =
  280, 282.5, 281,
  279, 278, 277.5 ;
}
