cfdm tutorial notebook
=============

Version <latest> for version <latest> of the CF conventions.
[//]: # (If the above line about versions changes its form then you should update the Makefile)

---

This notebook contains executable code examples from the [cfdm tutorial](https://ncas-cms.github.io/cfdm/tutorial.html).
------------------------------------------
---

Contents
---------------

* [**Import**](#Import)
* [**CF version**](#CF-version)
* [**Reading datasets**](#Reading-datasets)
* [**Inspection**](#Inspection)
  * [Minimal detail](#Minimal-detail)
  * [Medium detail](#Medium-detail)
  * [Full detail](#Full-detail)
* [**Properties**](#Properties)
* [**Data**](#Data)
  * [Indexing](#Indexing)
  * [Assignment](#Assignment)
  * [Data dimensions](#Data-dimensions)
* [**Subspacing**](#Subspacing)
* [**Metadata constructs**](#Metadata-constructs)
  * [Properties and data](#Properties-and-data)
  * [Domain axes](#Domain-axes)
  * [Cell methods](#Cell-methods)
  * [Components](#Components)
* [**NetCDF interface**](#NetCDF-interface)
* [**Writing to disk**](#Writing-to-disk)
  * [Scalar coordinate variables](#Scalar-coordinate-variables)
* [**Field construct creation**](#Field-construct-creation)
  * [Creating field constructs from metadata constructs](#Creating-field-constructs-from-metadata-constructs)
* [**Domain**](#Domain)
* [**Copying**](#Copying)
* [**Equality**](#Equality)
* [**External variables**](#External-variables)
* [**Compression**](#Compression)
* [**Discrete sampling geometries**](#Discrete-sampling-geometries)
* [**Gathering**](#Gathering)

---

##  Before you start

**0. [Install](https://ncas-cms.github.io/cfdm/installation.html) the cfdm package**

**1. Download the test files**

* [**file.nc**](https://ncas-cms.github.io/cfdm/_downloads/file.nc)
* [**parent.nc**](https://ncas-cms.github.io/cfdm/_downloads/parent.nc)
* [**external.nc**](https://ncas-cms.github.io/cfdm/_downloads/external.nc)
* [**contiguous.nc**](https://ncas-cms.github.io/cfdm/_downloads/contiguous.nc)
* [**gathered.nc**](https://ncas-cms.github.io/cfdm/_downloads/gathered.nc)

**2. Set the local directory which contains the test files**

By default it is assumed that they are in same directory as this notebook file.

In [1]:
DIRECTORY = '.'

**3. Ensure that  printing works equally well for Python 2 and 3**

In [2]:
from __future__ import print_function

---

## Import
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Import)  

In [3]:
import cfdm

---

## CF version
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#CF-version)  

In [4]:
cfdm.CF()

'1.7'

---

## Reading datasets
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Reading-datasets)

In [5]:
x = cfdm.read(DIRECTORY+'/file.nc')
type(x)
len(x)

2

---

## Inspection
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Inspection)

### Minimal detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Minimal-detail)  

In [6]:
x

[<Field: specific_humidity(latitude(5), longitude(8)) 1>,
 <Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>]

In [7]:
q = x[0]
t = x[1]
q

<Field: specific_humidity(latitude(5), longitude(8)) 1>

### Medium detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Medium-detail)  

In [8]:
print(q)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




In [9]:
print(t)

Field: air_temperature (ncvar%ta)
---------------------------------
Data            : air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K
Cell methods    : grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees) time(1): maximum
Field ancils    : air_temperature standard_error(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K
Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name:Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure%area(grid_longitude(9), grid_latitude(

### Full detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Full-detail)  

In [10]:
q.dump()

----------------------------------
Field: specific_humidity (ncvar%q)
----------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'specific_humidity'
units = '1'

Data(latitude(5), longitude(8)) = [[0.007, ..., 0.013]] 1

Cell Method: area: mean

Domain Axis: latitude(5)
Domain Axis: longitude(8)
Domain Axis: time(1)

Dimension coordinate: latitude
    standard_name = 'latitude'
    units = 'degrees_north'
    Data(latitude(5)) = [-75.0, ..., 75.0] degrees_north
    Bounds:Data(latitude(5), 2) = [[-90.0, ..., 90.0]] degrees_north

Dimension coordinate: longitude
    standard_name = 'longitude'
    units = 'degrees_east'
    Data(longitude(8)) = [22.5, ..., 337.5] degrees_east
    Bounds:Data(longitude(8), 2) = [[0.0, ..., 360.0]] degrees_east

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2019-01-01 00:00:00]



In [11]:
t.dump()

---------------------------------
Field: air_temperature (ncvar%ta)
---------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'air_temperature'
units = 'K'

Data(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) = [[[262.8, ..., 269.7]]] K

Cell Method: grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees)
Cell Method: time(1): maximum

Field Ancillary: air_temperature standard_error
    standard_name = 'air_temperature standard_error'
    units = 'K'
    Data(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K

Domain Axis: atmosphere_hybrid_height_coordinate(1)
Domain Axis: grid_latitude(10)
Domain Axis: grid_longitude(9)
Domain Axis: time(1)

Dimension coordinate: atmosphere_hybrid_height_coordinate
    computed_standard_name = 'altitude'
    standard_name = 'atmosphere_hybrid_height_coordinate'
    Data(atmosphere_hybrid_height_coordinate(1)) = [1.5]
    Bounds:Data(atmosphere_hybrid_h

---

## Properties
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Properties)  

In [12]:
t.properties()

{'Conventions': 'CF-1.7',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

---

In [13]:
t.has_property('standard_name')

True

In [14]:
t.get_property('standard_name')

'air_temperature'

In [15]:
t.del_property('standard_name')

'air_temperature'

In [16]:
t.get_property('standard_name', 'not set')

'not set'

In [17]:
t.set_property('standard_name', 'air_temperature')
t.get_property('standard_name', 'not set')

'air_temperature'

---

In [18]:
original = t.properties({'foo': 'bar', 'units': 'K'})
original

{'project': 'research',
 'units': 'K',
 'standard_name': 'air_temperature',
 'Conventions': 'CF-1.7'}

In [19]:
t.properties()

{'foo': 'bar', 'units': 'K'}

In [20]:
t.properties(original)

{'foo': 'bar', 'units': 'K'}

In [21]:
t.properties()

{'project': 'research',
 'units': 'K',
 'standard_name': 'air_temperature',
 'Conventions': 'CF-1.7'}

---

## Data
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Data)

In [22]:
t.get_data()

<Data(1, 10, 9): [[[262.8, ..., 269.7]]] K>

---

In [23]:
print(t.get_array())

[[[262.8 270.5 279.8 269.5 260.9 265.0 263.5 278.9 269.2]
  [272.7 268.4 279.5 278.9 263.8 263.3 274.2 265.7 279.5]
  [269.7 279.1 273.4 274.2 279.6 270.2 280.0 272.5 263.7]
  [261.7 260.6 270.8 260.3 265.6 279.4 276.9 267.6 260.6]
  [264.2 275.9 262.5 264.9 264.7 270.2 270.4 268.6 275.3]
  [263.9 263.8 272.1 263.7 272.2 264.2 260.0 263.5 270.2]
  [273.8 273.1 268.5 272.3 264.3 278.7 270.6 273.0 270.6]
  [267.9 273.5 279.8 260.3 261.2 275.3 271.2 260.8 268.9]
  [270.9 278.7 273.2 261.7 271.6 265.8 273.0 278.5 266.4]
  [276.4 264.2 276.3 266.1 276.1 268.1 277.0 273.4 269.7]]]


---

In [24]:
t.data.dtype

dtype('float64')

In [25]:
t.data.ndim

3

In [26]:
t.data.shape

(1, 10, 9)

In [27]:
t.data.size

90

### Indexing
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Indexing) 

In [28]:
data = t.data
data.shape

(1, 10, 9)

In [29]:
data[:, :, 1].shape

(1, 10, 1)

In [30]:
data[:, 0].shape

(1, 1, 9)

In [31]:
data[..., 6:3:-1, 3:6].shape

(1, 3, 3)

In [32]:
data[0, [2, 9], [4, 8]].shape

(1, 2, 2)

In [33]:
data[0, :, -2].shape

(1, 10, 1)

### Assignment
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Assignment) 

In [34]:
import numpy
t.data[:, :, 1] = -10
t.data[:, 0] = range(9)
t.data[..., 6:3:-1, 3:6] = numpy.arange(-18, -9).reshape(3, 3)
t.data[0, [2, 9], [4, 8]] =  cfdm.Data([[-2, -3]])
t.data[0, :, -2] = numpy.ma.masked
t.data[0, 5, -2] = -1
print(t.get_array())

[[[0.0 1.0 2.0 3.0 4.0 5.0 6.0 -- 8.0]
  [272.7 -10.0 279.5 278.9 263.8 263.3 274.2 -- 279.5]
  [269.7 -10.0 273.4 274.2 -2.0 270.2 280.0 -- -3.0]
  [261.7 -10.0 270.8 260.3 265.6 279.4 276.9 -- 260.6]
  [264.2 -10.0 262.5 -12.0 -11.0 -10.0 270.4 -- 275.3]
  [263.9 -10.0 272.1 -15.0 -14.0 -13.0 260.0 -1.0 270.2]
  [273.8 -10.0 268.5 -18.0 -17.0 -16.0 270.6 -- 270.6]
  [267.9 -10.0 279.8 260.3 261.2 275.3 271.2 -- 268.9]
  [270.9 -10.0 273.2 261.7 271.6 265.8 273.0 -- 266.4]
  [276.4 -10.0 276.3 266.1 -2.0 268.1 277.0 -- -3.0]]]


### Data dimensions
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Data-dimensions) 

In [35]:
t

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [36]:
t2 = t.squeeze(0)
t2

<Field: air_temperature(grid_latitude(10), grid_longitude(9)) K>

In [37]:
t2 = t2.expand_dims(axis='domainaxis3', position=1)
t2

<Field: air_temperature(grid_latitude(10), time(1), grid_longitude(9)) K>

In [38]:
t2.transpose([2, 0, 1])

<Field: air_temperature(grid_longitude(9), grid_latitude(10), time(1)) K>

---

## Subspacing
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Subspacing)

In [39]:
print(q)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




In [40]:
new = q[::-1, 0]
print(new)

Field: specific_humidity (ncvar%q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(1)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [75.0, ..., -75.0] degrees_north
                : longitude(1) = [22.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]




---

## Metadata constructs
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Metadata-constructs)

In [41]:
t.coordinate_references()

{'coordinatereference0': <CoordinateReference: atmosphere_hybrid_height_coordinate>,
 'coordinatereference1': <CoordinateReference: rotated_latitude_longitude>}

In [42]:
t.dimension_coordinates()

{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

----

In [43]:
q.constructs()

{'cellmethod0': <CellMethod: area: mean>,
 'dimensioncoordinate0': <DimensionCoordinate: latitude(5) degrees_north>,
 'dimensioncoordinate1': <DimensionCoordinate: longitude(8) degrees_east>,
 'dimensioncoordinate2': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainaxis0': <DomainAxis: 5>,
 'domainaxis1': <DomainAxis: 8>,
 'domainaxis2': <DomainAxis: 1>}

In [44]:
t.constructs()

{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
 'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name:Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>,
 'cellmethod0': <CellMethod: domainaxis1: domainaxis2: mean where land (interval: 0.1 degrees)>,
 'cellmethod1': <CellMethod: domainaxis3: maximum>,
 'coordinatereference0': <CoordinateReference: atmosphere_hybrid_height_coordinate>,
 'coordinatereference1': <CoordinateReference: rotated_latitude_longitude>,
 'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainancillary0': <DomainAncillary: ncvar%a(1) m>,
 'domainancillary1': <Doma

---

In [45]:
t.constructs('air_temperature standard_error')

{'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}

In [46]:
t.constructs(construct_type='dimension_coordinate')

{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

In [47]:
t.constructs(axes=['domainaxis1'])

{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
 'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name:Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'domainancillary2': <DomainAncillary: surface_altitude(10, 9) m>,
 'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}

In [48]:
t.constructs(axes=['domainaxis3'])

{'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}

In [49]:
t.constructs(construct_type='dimension_coordinate', axes=['domainaxis1'])

{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>}

In [50]:
t.constructs('wavelength')

{}

---

In [51]:
 t.constructs(construct_type='cell_measure')

{'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>}

In [52]:
t.cell_measures()

{'cellmeasure0': <CellMeasure: measure%area(9, 10) km2>}

----

In [53]:
t.constructs(cid='domainancillary2')

{'domainancillary2': <DomainAncillary: surface_altitude(10, 9) m>}

In [54]:
t.constructs('cid%cellmethod1')

{'cellmethod1': <CellMethod: domainaxis3: maximum>}

In [55]:
t.constructs(cid='auxiliarycoordinate999')

{}

---

In [56]:
t.has_construct('latitude')

True

In [57]:
t.get_construct('latitude')

<AuxiliaryCoordinate: latitude(10, 9) degrees_N>

In [58]:
t.get_construct('units:km2')

<CellMeasure: measure%area(9, 10) km2>

In [59]:
t.constructs('units:degrees')

{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>}

In [60]:
try:
    t.get_construct('units:degrees')
except ValueError:
    print('ValueError: More than one construct meets criteria')

ValueError: More than one construct meets criteria


In [61]:
t.has_construct('units:degrees')

False

### Properties and data
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Properties-and-data)

In [62]:
lon = q.get_construct('longitude')   
lon

<DimensionCoordinate: longitude(8) degrees_east>

In [63]:
lon.set_property('long_name', 'Longitude')
lon.properties()

{'units': 'degrees_east',
 'long_name': 'Longitude',
 'standard_name': 'longitude'}

In [64]:
lon.data[2]
lon.data[2] = 133.33
print(lon.get_array())

[22.5 67.5 133.33 157.5 202.5 247.5 292.5 337.5]


### Domain axes
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Domain-axes)

In [65]:
t.construct_axes()

AttributeError: 'Field' object has no attribute 'construct_axes'

---

In [ ]:
t.domain_axes()

In [ ]:
t

In [ ]:
t.data.shape

In [ ]:
t.get_data_axes()

### Cell methods
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Cell-methods)

In [ ]:
t.cell_methods()

### Components

[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Components)

In [ ]:
lon = t.get_construct('grid_longitude')
bounds = lon.get_bounds()
bounds

In [ ]:
bounds.properties()

In [ ]:
bounds.get_data()
print(bounds.get_array())

In [ ]:
crs = t.get_construct('rotated_latitude_longitude')
crs.datum

In [ ]:
crs.datum.parameters()

In [ ]:
crs = t.get_construct('atmosphere_hybrid_height_coordinate',
                          construct_type='coordinate_reference')
crs.coordinate_conversion.domain_ancillaries()

---

## NetCDF interface
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#NetCDF-interface)

In [ ]:
t.constructs('ncvar%b')

In [ ]:
t.get_construct('ncvar%x')

In [ ]:
t.get_construct('ncdim%x')

---

In [ ]:
q.nc_get_variable()

In [ ]:
q.nc_global_attributes()

In [ ]:
q.nc_unlimited_dimensions()

In [ ]:
q.nc_set_variable('humidity')
q.nc_get_variable()

---

## Writing to disk
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Writing-to-disk)

In [ ]:
print(q)

In [ ]:
cfdm.write(q, 'q_file.nc')

In [ ]:
!ncdump -h q_file.nc

---

In [ ]:
x

In [ ]:
cfdm.write(x, 'new_file.nc')

### Scalar coordinate variables
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Scalar-coordinate-variables)

In [ ]:
print(q)

In [ ]:
q.get_construct_axes('time')

In [ ]:
q2 = q.expand_dims(axis='domainaxis2')
q2

In [ ]:
cfdm.write(q2, 'q2_file.nc')

In [ ]:
!ncdump -h q2_file.nc

---

## Field construct creation
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Field-construct-creation)

In [ ]:
p = cfdm.Field(properties={'standard_name': 'precipitation_flux'})
p

In [ ]:
dc = cfdm.DimensionCoordinate(properties={'long_name': 'Longitude'},
                              data=cfdm.Data([0, 1, 2.]))
dc

In [ ]:
fa = cfdm.FieldAncillary(
           properties={'standard_name': 'precipitation_flux status_flag'},
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

---

In [ ]:
p = cfdm.Field()
p

In [ ]:
p.set_property('standard_name', 'precipitation_flux')
p

In [ ]:
dc = cfdm.DimensionCoordinate()
dc

In [ ]:
dc.set_property('long_name', 'Longitude')
dc.set_data(cfdm.Data([1, 2, 3.]))
dc

In [ ]:
fa = cfdm.FieldAncillary(
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

In [ ]:
fa.set_property('standard_name', 'precipitation_flux status_flag')
fa

---

In [ ]:
longitude_axis = p.set_construct(cfdm.DomainAxis(3))
longitude_axis

In [ ]:
cid = p.set_construct(dc, axes=[longitude_axis])
cid

In [ ]:
cm = cfdm.CellMethod(axes=[longitude_axis],
                     properties={'method': 'minimum'})
p.set_construct(cm)
print(p)

---

In [ ]:
import numpy
import cfdm

# Initialise the field with properties
Q = cfdm.Field(properties={'project': 'research',
                           'standard_name': 'specific_humidity',
                           'units': '1'})

# Create the domain axes
domain_axisT = cfdm.DomainAxis(1)
domain_axisY = cfdm.DomainAxis(5)
domain_axisX = cfdm.DomainAxis(8)

# Insert the domain axes into the field. The set_constuct method
# returns the domain axis construct identifier that will be used
# later to specify which domain axis corresponds to which dimension
# coordinate construct.  
axisT = Q.set_construct(domain_axisT)
axisY = Q.set_construct(domain_axisY)
axisX = Q.set_construct(domain_axisX)

# Field data
data = cfdm.Data(numpy.arange(40.).reshape(5, 8))
Q.set_data(data, axes=[axisY, axisX])

# Create the cell methods
cell_method1 = cfdm.CellMethod(axes=['area'], properties={'method': 'mean'})

cell_method2 = cfdm.CellMethod()
cell_method2.set_axes([axisT])
cell_method2.properties({'method': 'maximum'})

# Insert the cell methods into the field in the same order that
# their methods were applied to the data
Q.set_construct(cell_method1)
Q.set_construct(cell_method2)

# Create the dimension Coordinates
dimT = cfdm.DimensionCoordinate(
         properties={'standard_name': 'time',
                     'units': 'days since 2018-12-01'},
         data=cfdm.Data([15.5]),
         bounds=cfdm.Bounds(data=cfdm.Data([[0,31.]])))

dimY = cfdm.DimensionCoordinate(properties={'standard_name': 'latitude',
                                    'units': 'degrees_north'})
array = numpy.arange(5.)
dimY.set_data(cfdm.Data(array))
bounds_array = numpy.empty((5, 2))
bounds_array[:, 0] = array - 0.5
bounds_array[:, 1] = array + 0.5
bounds = cfdm.Bounds(data=cfdm.Data(bounds_array))
dimY.set_bounds(bounds)

dimX = cfdm.DimensionCoordinate(data=cfdm.Data(numpy.arange(8.)))
dimX.properties({'standard_name': 'longitude',
                 'units': 'degrees_east'})

# Insert the dimension coordinates into the field, specifying to
# which domain axis each one corresponds
Q.set_construct(dimT, axes=[axisT])
Q.set_construct(dimY, axes=[axisY])
Q.set_construct(dimX, axes=[axisX])

In [ ]:
Q.dump()

In [ ]:
Q.nc_set_variable('q')

domain_axisT.nc_set_dimension('time')
domain_axisY.nc_set_dimension('lat')
domain_axisX.nc_set_dimension('lon')

dimT.nc_set_variable('time')
dimY.nc_set_variable('lat')
dimX.nc_set_variable('lon')

---

In [ ]:
import numpy
import cfdm

# Initialize the field
tas = cfdm.Field(
    properties={'project': 'research',
                'standard_name': 'air_temperature',
                'units': 'K'})

# Create and set domain axes
axis_T = tas.set_construct(cfdm.DomainAxis(1))
axis_Z = tas.set_construct(cfdm.DomainAxis(1))
axis_Y = tas.set_construct(cfdm.DomainAxis(10))
axis_X = tas.set_construct(cfdm.DomainAxis(9))

# Set the field data
tas.set_data(cfdm.Data(numpy.arange(90.).reshape(10, 9)),
             axes=[axis_Y, axis_X])

# Create and set the cell methods
cell_method1 = cfdm.CellMethod(
          axes=[axis_Y, axis_X],
          properties={'method': 'mean',
                      'where': 'land',
                      'intervals': [cfdm.Data(0.1, units='degrees')]})

cell_method2 = cfdm.CellMethod(
                 axes=[axis_T],
                 properties={'method': 'maximum'})

tas.set_construct(cell_method1)
tas.set_construct(cell_method2)

# Create and set the field ancillaries
field_ancillary = cfdm.FieldAncillary(
             properties={'standard_name': 'air_temperature standard_error',
                          'units': 'K'},
             data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

tas.set_construct(field_ancillary, axes=[axis_Y, axis_X])

# Create and set the dimension coordinates
dimension_coordinate_T = cfdm.DimensionCoordinate(
                           properties={'standard_name': 'time',
                                       'units': 'days since 2018-12-01'},
                           data=cfdm.Data([15.5]),
                           bounds=cfdm.Bounds(data=cfdm.Data([[0., 31]])))

dimension_coordinate_Z = cfdm.DimensionCoordinate(
        properties={'computed_standard_name': 'altitude',
                    'standard_name': 'atmosphere_hybrid_height_coordinate'},
        data = cfdm.Data([1.5]),
        bounds=cfdm.Bounds(data=cfdm.Data([[1.0, 2.0]])))

dimension_coordinate_Y = cfdm.DimensionCoordinate(
        properties={'standard_name': 'grid_latitude',
                    'units': 'degrees'},
        data=cfdm.Data(numpy.arange(10.)),
        bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(20).reshape(10, 2))))

dimension_coordinate_X = cfdm.DimensionCoordinate(
        properties={'standard_name': 'grid_longitude',
                    'units': 'degrees'},
    data=cfdm.Data(numpy.arange(9.)),
    bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(18).reshape(9, 2))))

dim_T = tas.set_construct(dimension_coordinate_T, axes=[axis_T])
dim_Z = tas.set_construct(dimension_coordinate_Z, axes=[axis_Z])
dim_Y = tas.set_construct(dimension_coordinate_Y, axes=[axis_Y])
dim_X = tas.set_construct(dimension_coordinate_X, axes=[axis_X])

# Create and set the auxiliary coordinates
auxiliary_coordinate_lat = cfdm.AuxiliaryCoordinate(
                      properties={'standard_name': 'latitude',
                                  'units': 'degrees_north'},
                      data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

auxiliary_coordinate_lon = cfdm.AuxiliaryCoordinate(
                  properties={'standard_name': 'longitude',
                              'units': 'degrees_east'},
                  data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

array = numpy.ma.array(list('abcdefghij'), dtype='S')
array[0] = numpy.ma.masked
auxiliary_coordinate_name = cfdm.AuxiliaryCoordinate(
                       properties={'long_name': 'Grid latitude name'},
                       data=cfdm.Data(array))

aux_LAT  = tas.set_construct(auxiliary_coordinate_lat, axes=[axis_Y, axis_X])
aux_LON  = tas.set_construct(auxiliary_coordinate_lon, axes=[axis_X, axis_Y])
aux_NAME = tas.set_construct(auxiliary_coordinate_name, axes=[axis_Y])

# Create and set domain ancillaries
domain_ancillary_a = cfdm.DomainAncillary(
                   properties={'units': 'm'},
                   data=cfdm.Data([10.]),
                   bounds=cfdm.Bounds(data=cfdm.Data([[5., 15.]])))

domain_ancillary_b = cfdm.DomainAncillary(
                       properties={'units': '1'},
                       data=cfdm.Data([20.]),
                       bounds=cfdm.Bounds(data=cfdm.Data([[14, 26.]])))

domain_ancillary_orog = cfdm.DomainAncillary(
                          properties={'standard_name': 'surface_altitude',
                                     'units': 'm'},
                          data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

domain_anc_A    = tas.set_construct(domain_ancillary_a, axes=[axis_Z])
domain_anc_B    = tas.set_construct(domain_ancillary_b, axes=[axis_Z])
domain_anc_OROG = tas.set_construct(domain_ancillary_orog, axes=[axis_Y, axis_X])

# Create and set the coordinate references
datum = cfdm.Datum(parameters={'earth_radius': 6371007.})

coordinate_conversion_h = cfdm.CoordinateConversion(
              parameters={'grid_mapping_name': 'rotated_latitude_longitude',
                          'grid_north_pole_latitude': 38.0,
                          'grid_north_pole_longitude': 190.0})

horizontal_crs = cfdm.CoordinateReference(
                   datum=datum,
                   coordinate_conversion=coordinate_conversion_h,
                   coordinates=[dim_X,
                                dim_Y,
                                aux_LAT,
                                aux_LON])

coordinate_conversion_v = cfdm.CoordinateConversion(
         parameters={'standard_name': 'atmosphere_hybrid_height_coordinate',
                     'computed_standard_name': 'altitude'},
         domain_ancillaries={'a': domain_anc_A,
                             'b': domain_anc_B,
                             'orog': domain_anc_OROG})

vertical_crs = cfdm.CoordinateReference(
                 datum=datum,
                 coordinate_conversion=coordinate_conversion_v,
                 coordinates=[dim_Z])

tas.set_construct(horizontal_crs)
tas.set_construct(vertical_crs)

# Create and set the cell measures
cell_measure = cfdm.CellMeasure(measure='area',
                 properties={'units': 'km2'},
                 data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

tas.set_construct(cell_measure, axes=[axis_X, axis_Y])

In [ ]:
print(tas)

---

### Creating field constructs from metadata constructs
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Creating-field-constructs-from-metadata-constructs)

In [ ]:
orog = tas.create_field('surface_altitude')
print(orog)

In [ ]:
orog1 = tas.create_field('surface_altitude', domain=False)
print(orog1)

---

In [ ]:
cfdm.write(tas, 'tas.nc')
fields = cfdm.read('tas.nc', create_field='domain_ancillary')
fields

In [ ]:
print(fields[3])

---

## Domain
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Domain)

In [ ]:
domain = t.get_domain()
domain

In [ ]:
print(domain)

In [ ]:
domain.dump()

In [ ]:
domain.get_construct('latitude').set_property('test', 'set by domain')

In [ ]:
t.get_construct('latitude').get_property('test')

In [ ]:
t.get_construct('latitude').set_property('test', 'set by field')

In [ ]:
domain.get_construct('latitude').get_property('test')

In [ ]:
domain.get_construct('latitude').del_property('test')

In [ ]:
t.get_construct('latitude').has_property('test')

---

## Copying
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#Copying)

In [ ]:
t

In [ ]:
u = t.copy()
u

In [ ]:
u.data[0, 0, 0] = -1e30
print(u.data[0, 0, 0])

In [ ]:
print(t.data[0, 0, 0])

In [ ]:
u.del_construct('grid_latitude')

In [ ]:
u.constructs('grid_latitude')

In [ ]:
t.constructs('grid_latitude')

---

In [ ]:
import copy
u = copy.deepcopy(t)

---

In [ ]:
orog = t.get_construct('surface_altitude').copy()
orog

---

## Equality
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#equality)

In [ ]:
t.equals(t)

In [ ]:
t.equals(t.copy())

In [ ]:
t.equals(t[...])

In [ ]:
t.equals(q)

In [ ]:
t.equals(q, traceback=True)

----

In [ ]:
orog = t.get_construct('surface_altitude')
orog.equals(orog.copy())

---

In [ ]:
cfdm.ATOL()

In [ ]:
cfdm.RTOL()

In [ ]:
original = cfdm.RTOL(0.00001)
cfdm.RTOL()

In [ ]:
cfdm.RTOL(original)

In [ ]:
cfdm.RTOL()

---

## External variables
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#external-variables)

In [ ]:
!ncdump -h parent.nc

In [ ]:
!ncdump -h external.nc 

In [ ]:
u = cfdm.read(DIRECTORY+'/parent.nc')[0]
print(u)

In [ ]:
area = u.get_construct('measure%area')
area

In [ ]:
area.nc_external()

In [ ]:
area.nc_get_variable()

In [ ]:
area.properties()

In [ ]:
area.has_data()

---

In [ ]:
g = cfdm.read(DIRECTORY+'/parent.nc', external_files=DIRECTORY+'/external.nc')[0]
print(g)

In [ ]:
area = g.get_construct('cell_area')
area

In [ ]:
area.nc_external()

In [ ]:
area.nc_get_variable()

In [ ]:
area.properties()

In [ ]:
area.get_data()

---

In [ ]:
area.nc_external(True)

In [ ]:
cfdm.write(g, 'new_parent.nc', external_file='new_external.nc')

---

## Compression
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#compression)

---

## Discrete sampling geometries
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#discrete-sampling-geometries)

In [ ]:
!ncdump -h contiguous.nc

---

In [ ]:
h = cfdm.read(DIRECTORY+'/contiguous.nc')[0]
print(h)

In [ ]:
print(h.get_array())

In [ ]:
h.data.get_compression_type()

In [ ]:
print(h.data.get_compressed_array())

In [ ]:
count_variable = h.data.get_count_variable()
count_variable

In [ ]:
print(count_variable.get_array())

---

In [ ]:
station = h[1]
station

In [ ]:
print(station.get_array())

---

In [ ]:
h.data.get_compression_type()

In [ ]:
h.data[1, 2] = -9
print(h.get_array())

In [ ]:
h.data.get_compression_type()

---

In [ ]:
import numpy
import cfdm

# Define the ragged array values
ragged_array = numpy.array([280, 282.5, 281, 279, 278, 279.5],
                           dtype='float32')

# Define the count array values
count_array = [2, 4]

# Create the count variable
count_variable = cfdm.Count(data=cfdm.Data(count_array))
count_variable.set_property('long_name', 'number of obs for this timeseries')

# Create the contiguous ragged array object
array = cfdm.RaggedContiguousArray(
                 compressed_array=cfdm.NumpyArray(ragged_array),
                 shape=(2, 4), size=8, ndim=2,
                 count_variable=count_variable)

# Create the field construct with the domain axes and the ragged
# array
T = cfdm.Field()
T.properties({'standard_name': 'air_temperature',
                'units': 'K'})

# Create the domain axis constructs for the uncompressed array
X = T.set_construct(cfdm.DomainAxis(4))
Y = T.set_construct(cfdm.DomainAxis(2))

# Set the data for the field
T.set_data(cfdm.Data(array), axes=[Y, X])

---

In [ ]:
T

In [ ]:
print(T.get_array())

In [ ]:
T.data.get_compression_type()

In [ ]:
print(T.data.get_compressed_array())

In [ ]:
count_variable = T.data.get_count_variable()
count_variable

In [ ]:
print(count_variable.get_array())

In [ ]:
cfdm.write(T, 'T_contiguous.nc')

In [ ]:
!ncdump T_contiguous.nc

---

## Gathering
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#gathering)

In [ ]:
p = cfdm.read(DIRECTORY+'/gathered.nc')[0]
print(p)

In [ ]:
print(p.get_array())

In [ ]:
p.data.get_compression_type()

In [ ]:
print(p.data.get_compressed_array())

In [ ]:
list_variable = p.data.get_list_variable()
list_variable

In [ ]:
print(list_variable.get_array())

---

In [ ]:
p[0]

In [ ]:
p[1, :, 3:5]

---

In [ ]:
p.data.get_compression_type()

In [ ]:
p.data[1] = -9

In [ ]:
p.data.get_compression_type()

---

In [ ]:
import numpy   
import cfdm

# Define the gathered values
gathered_array = numpy.array([[2, 1, 3], [4, 0, 5]],
                             dtype='float32')

# Define the list array values
list_array = [1, 4, 5]

# Create the list variable
list_variable = cfdm.List(data=cfdm.Data(list_array))

# Create the gathered array object
array = cfdm.GatheredArray(
                 compressed_array=cfdm.NumpyArray(gathered_array),
         compressed_dimension=1,
                 shape=(2, 3, 2), size=12, ndim=3,
                 list_variable=list_variable)

# Create the field construct with the domain axes and the gathered
# array
P = cfdm.Field(properties={'standard_name': 'precipitation_flux',
                           'units': 'kg m-2 s-1'})


# Create the domain axis constructs for the uncompressed array
T = P.set_construct(cfdm.DomainAxis(2))
Y = P.set_construct(cfdm.DomainAxis(3))
X = P.set_construct(cfdm.DomainAxis(2))

# Set the data for the field
P.set_data(cfdm.Data(array), axes=[T, Y, X])                 

---

In [ ]:
P

In [ ]:
print(P.get_array())

In [ ]:
P.data.get_compression_type()

In [ ]:
print(P.data.get_compressed_array())

In [ ]:
list_variable = P.data.get_list_variable()
list_variable 

In [ ]:
print(list_variable.get_array())

In [ ]:
cfdm.write(P, 'P_gathered.nc')

In [ ]:
!ncdump P_gathered.nc

---
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html)  