cfdm tutorial notebook
=============

Version <latest> for version <latest> of the CF conventions.
    
[//]: # (If the above line about versions changes its form then you should update the Makefile)

---

This notebook contains executable code examples from the [cfdm tutorial](https://ncas-cms.github.io/cfdm/tutorial.html).
------------------------------------------
---

Contents
---------------

* [**Import**](#Import)
* [**CF version**](#CF-version)
* [**Reading datasets**](#Reading-datasets)
* [**Inspection**](#Inspection)
  * [Minimal detail](#Minimal-detail)
  * [Medium detail](#Medium-detail)
  * [Full detail](#Full-detail)
* [**Properties**](#Properties)
* [**Metadata constructs 1**](#Metadata-constructs-1)
* [**Data**](#Data)
  * [Data axes](#Data-axes)
  * [Indexing](#Indexing)
  * [Assignment](#Assignment)
  * [Manipulating dimensions](#Manipulating-dimensions)
* [**Subspacing**](#Subspacing)
* [**Metadata constructs 2**](#Metadata-constructs-2)
  * [Accessing an individual metadata construct](#Accessing-an-individual-metadata-construct)
  * [Metadata construct properties](#Metadata-construct-properties)
  * [Metadata construct data](#Metadata-construct-data)
* [**Domain**](#Domain) 
* [**Domain axes**](#Domain-axes)
* [**Coordinates**](#Coordinates)
* [**Domain ancillaries**](#Domain-ancillaries)
* [**Coordinate systems**](#Coordinate-systems)
* [**Cell methods**](#Cell-methods)
* [**Field construct creation**](#Field-construct-creation)
  * [Manual creation](#Manual-creation)
  * [Creating data from an array on disk](#Creating-data-from-an-array-on-disk)
  * [Creation by conversion](#Creation-by-conversion)
  * [Creation by reading](#Creation-by-reading)
* [**Copying**](#Copying)
* [**Equality**](#Equality)
* [**NetCDF interface**](#NetCDF-interface)
* [**Writing to disk**](#Writing-to-disk)
  * [Scalar coordinate variables](#Scalar-coordinate-variables)
* [**Field construct creation**](#Field-construct-creation)
  * [Creating field constructs from metadata constructs](#Creating-field-constructs-from-metadata-constructs)
* [**External variables**](#External-variables)
* [**Compression**](#Compression)
* [**Discrete sampling geometries**](#Discrete-sampling-geometries)
* [**Gathering**](#Gathering)

---

##  Before you start

**0. [Install](https://ncas-cms.github.io/cfdm/installation.html) the cfdm package**

**1. Download the test files**

* [**file.nc**](https://ncas-cms.github.io/cfdm/_downloads/file.nc)
* [**parent.nc**](https://ncas-cms.github.io/cfdm/_downloads/parent.nc)
* [**external.nc**](https://ncas-cms.github.io/cfdm/_downloads/external.nc)
* [**contiguous.nc**](https://ncas-cms.github.io/cfdm/_downloads/contiguous.nc)
* [**gathered.nc**](https://ncas-cms.github.io/cfdm/_downloads/gathered.nc)

**2. Set the local directory which contains the test files**

By default it is assumed that they are in same directory as this notebook file.

In [1]:
DIRECTORY = '.'

**3. Ensure that  printing works equally well for Python 2 and 3**

In [2]:
from __future__ import print_function

---

## Import
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#import)  

In [3]:
import cfdm

---

## CF version
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#cf-version)  

In [4]:
cfdm.CF()

'1.7'

---

## Reading datasets
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#reading-datasets)

In [5]:
x = cfdm.read(DIRECTORY+'/file.nc')
print(type(x))

<type 'list'>


In [6]:
len(x)

2

---

## Inspection
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#inspection)

### Minimal detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#minimal-detail)  

In [7]:
x

[<Field: specific_humidity(latitude(5), longitude(8)) 1>,
 <Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>]

In [8]:
q = x[0]
t = x[1]
q

<Field: specific_humidity(latitude(5), longitude(8)) 1>

### Medium detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#medium-detail)  

In [9]:
print(q)

Field: specific_humidity (ncvar:q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]



In [10]:
print(t)

Field: air_temperature (ncvar:ta)
---------------------------------
Data            : air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K
Cell methods    : grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees) time(1): maximum
Field ancils    : air_temperature standard_error(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K
Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name=Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure:area(grid_longitude(9), grid_latitude(

### Full detail
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#full-detail)  

In [11]:
q.dump()

----------------------------------
Field: specific_humidity (ncvar:q)
----------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'specific_humidity'
units = '1'

Data(latitude(5), longitude(8)) = [[0.007, ..., 0.013]] 1

Cell Method: area: mean

Domain Axis: latitude(5)
Domain Axis: longitude(8)
Domain Axis: time(1)

Dimension coordinate: latitude
    standard_name = 'latitude'
    units = 'degrees_north'
    Data(latitude(5)) = [-75.0, ..., 75.0] degrees_north
    Bounds:Data(latitude(5), 2) = [[-90.0, ..., 90.0]] degrees_north

Dimension coordinate: longitude
    standard_name = 'longitude'
    units = 'degrees_east'
    Data(longitude(8)) = [22.5, ..., 337.5] degrees_east
    Bounds:Data(longitude(8), 2) = [[0.0, ..., 360.0]] degrees_east

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2019-01-01 00:00:00]



In [12]:
t.dump()

---------------------------------
Field: air_temperature (ncvar:ta)
---------------------------------
Conventions = 'CF-1.7'
project = 'research'
standard_name = 'air_temperature'
units = 'K'

Data(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) = [[[262.8, ..., 269.7]]] K

Cell Method: grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees)
Cell Method: time(1): maximum

Field Ancillary: air_temperature standard_error
    standard_name = 'air_temperature standard_error'
    units = 'K'
    Data(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K

Domain Axis: atmosphere_hybrid_height_coordinate(1)
Domain Axis: grid_latitude(10)
Domain Axis: grid_longitude(9)
Domain Axis: time(1)

Dimension coordinate: atmosphere_hybrid_height_coordinate
    computed_standard_name = 'altitude'
    standard_name = 'atmosphere_hybrid_height_coordinate'
    Data(atmosphere_hybrid_height_coordinate(1)) = [1.5]
    Bounds:Data(atmosphere_hybrid_h

---

## Properties
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#properties)  

In [13]:
t.properties()

{'Conventions': 'CF-1.7',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

---

In [14]:
t.has_property('standard_name')

True

In [15]:
t.get_property('standard_name')

'air_temperature'

In [16]:
t.del_property('standard_name')

'air_temperature'

In [17]:
t.get_property('standard_name', default='not set')

'not set'

In [18]:
t.set_property('standard_name', 'air_temperature')
t.get_property('standard_name', default='not set')

'air_temperature'

---

In [19]:
original = t.properties()

In [20]:
original 

{'Conventions': 'CF-1.7',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

In [21]:
t.set_properties({'foo': 'bar', 'units': 'K'})

In [22]:
t.properties()

{'Conventions': 'CF-1.7',
 'foo': 'bar',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

In [23]:
t.clear_properties()

{'Conventions': 'CF-1.7',
 'foo': 'bar',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

In [24]:
t.properties()

{}

In [25]:
t.set_properties(original)
t.properties()

{'Conventions': 'CF-1.7',
 'project': 'research',
 'standard_name': 'air_temperature',
 'units': 'K'}

---

## Metadata constructs 1
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#metadata-constructs-1)

In [26]:
t.coordinate_references

<Constructs: coordinate_reference(2)>

In [27]:
print(t.coordinate_references)

Constructs:
{'coordinatereference0': <CoordinateReference: atmosphere_hybrid_height_coordinate>,
 'coordinatereference1': <CoordinateReference: rotated_latitude_longitude>}


In [28]:
t.coordinate_references.keys()

['coordinatereference0', 'coordinatereference1']

In [29]:
for key, value in t.coordinate_references.items():
    print(key, value)

coordinatereference1 rotated_latitude_longitude
coordinatereference0 atmosphere_hybrid_height_coordinate


----

In [30]:
print(t.dimension_coordinates)

Constructs:
{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}


In [31]:
print(t.domain_axes)

Constructs:
{'domainaxis0': <DomainAxis: size(1)>,
 'domainaxis1': <DomainAxis: size(10)>,
 'domainaxis2': <DomainAxis: size(9)>,
 'domainaxis3': <DomainAxis: size(1)>}


----

In [32]:
q.constructs

<Constructs: cell_method(1), dimension_coordinate(3), domain_axis(3)>

In [33]:
print(q.constructs)

Constructs:
{'cellmethod0': <CellMethod: area: mean>,
 'dimensioncoordinate0': <DimensionCoordinate: latitude(5) degrees_north>,
 'dimensioncoordinate1': <DimensionCoordinate: longitude(8) degrees_east>,
 'dimensioncoordinate2': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainaxis0': <DomainAxis: size(5)>,
 'domainaxis1': <DomainAxis: size(8)>,
 'domainaxis2': <DomainAxis: size(1)>}


In [34]:
t.constructs

<Constructs: auxiliary_coordinate(3), cell_measure(1), cell_method(2), coordinate_reference(2), dimension_coordinate(4), domain_ancillary(3), domain_axis(4), field_ancillary(1)>

In [35]:
print(t.constructs)

Constructs:
{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
 'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name=Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>,
 'cellmethod0': <CellMethod: domainaxis1: domainaxis2: mean where land (interval: 0.1 degrees)>,
 'cellmethod1': <CellMethod: domainaxis3: maximum>,
 'coordinatereference0': <CoordinateReference: atmosphere_hybrid_height_coordinate>,
 'coordinatereference1': <CoordinateReference: rotated_latitude_longitude>,
 'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >,
 'domainancillary0': <DomainAncillary: ncvar%a(1) m>,
 'domainancill

----

## Data
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#data)

In [36]:
d = t.data
d

<Data(1, 10, 9): [[[262.8, ..., 269.7]]] K>

---

In [37]:
print(t.data.array)

[[[ 262.8  270.5  279.8  269.5  260.9  265.   263.5  278.9  269.2]
  [ 272.7  268.4  279.5  278.9  263.8  263.3  274.2  265.7  279.5]
  [ 269.7  279.1  273.4  274.2  279.6  270.2  280.   272.5  263.7]
  [ 261.7  260.6  270.8  260.3  265.6  279.4  276.9  267.6  260.6]
  [ 264.2  275.9  262.5  264.9  264.7  270.2  270.4  268.6  275.3]
  [ 263.9  263.8  272.1  263.7  272.2  264.2  260.   263.5  270.2]
  [ 273.8  273.1  268.5  272.3  264.3  278.7  270.6  273.   270.6]
  [ 267.9  273.5  279.8  260.3  261.2  275.3  271.2  260.8  268.9]
  [ 270.9  278.7  273.2  261.7  271.6  265.8  273.   278.5  266.4]
  [ 276.4  264.2  276.3  266.1  276.1  268.1  277.   273.4  269.7]]]


---

In [38]:
t.data.dtype

dtype('float64')

In [39]:
t.data.ndim

3

In [40]:
t.data.shape

(1, 10, 9)

In [41]:
t.data.size

90

----

### Data axes
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#data-axes)

In [42]:
print(t.domain_axes)

Constructs:
{'domainaxis0': <DomainAxis: size(1)>,
 'domainaxis1': <DomainAxis: size(10)>,
 'domainaxis2': <DomainAxis: size(9)>,
 'domainaxis3': <DomainAxis: size(1)>}


In [43]:
t

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [44]:
t.data.shape

(1, 10, 9)

In [45]:
t.get_data_axes()

('domainaxis0', 'domainaxis1', 'domainaxis2')

----

### Indexing
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#indexing) 

In [46]:
data = t.data
data.shape

(1, 10, 9)

In [47]:
data[:, :, 1].shape

(1, 10, 1)

In [48]:
data[:, 0].shape

(1, 1, 9)

In [49]:
data[..., 6:3:-1, 3:6].shape

(1, 3, 3)

In [50]:
data[0, [2, 9], [4, 8]].shape

(1, 2, 2)

In [51]:
data[0, :, -2].shape

(1, 10, 1)

### Assignment
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#assignment) 

In [52]:
import numpy
t.data[:, 0, 0] = -1
t.data[:, :, 1] = -2
t.data[..., 6:3:-1, 3:6] = -3
print(t.data.array)

[[[  -1.    -2.   279.8  269.5  260.9  265.   263.5  278.9  269.2]
  [ 272.7   -2.   279.5  278.9  263.8  263.3  274.2  265.7  279.5]
  [ 269.7   -2.   273.4  274.2  279.6  270.2  280.   272.5  263.7]
  [ 261.7   -2.   270.8  260.3  265.6  279.4  276.9  267.6  260.6]
  [ 264.2   -2.   262.5   -3.    -3.    -3.   270.4  268.6  275.3]
  [ 263.9   -2.   272.1   -3.    -3.    -3.   260.   263.5  270.2]
  [ 273.8   -2.   268.5   -3.    -3.    -3.   270.6  273.   270.6]
  [ 267.9   -2.   279.8  260.3  261.2  275.3  271.2  260.8  268.9]
  [ 270.9   -2.   273.2  261.7  271.6  265.8  273.   278.5  266.4]
  [ 276.4   -2.   276.3  266.1  276.1  268.1  277.   273.4  269.7]]]


----

In [53]:
t.data[..., 6:3:-1, 3:6] = numpy.arange(9).reshape(3, 3)
t.data[0, [2, 9], [4, 8]] =  cfdm.Data([[-4, -5]])
print(t.data.array)

[[[  -1.    -2.   279.8  269.5  260.9  265.   263.5  278.9  269.2]
  [ 272.7   -2.   279.5  278.9  263.8  263.3  274.2  265.7  279.5]
  [ 269.7   -2.   273.4  274.2   -4.   270.2  280.   272.5   -5. ]
  [ 261.7   -2.   270.8  260.3  265.6  279.4  276.9  267.6  260.6]
  [ 264.2   -2.   262.5    6.     7.     8.   270.4  268.6  275.3]
  [ 263.9   -2.   272.1    3.     4.     5.   260.   263.5  270.2]
  [ 273.8   -2.   268.5    0.     1.     2.   270.6  273.   270.6]
  [ 267.9   -2.   279.8  260.3  261.2  275.3  271.2  260.8  268.9]
  [ 270.9   -2.   273.2  261.7  271.6  265.8  273.   278.5  266.4]
  [ 276.4   -2.   276.3  266.1   -4.   268.1  277.   273.4   -5. ]]]


----

In [54]:
t.data[0, :, -2] = numpy.ma.masked
t.data[0, 5, -2] = -6
print(t.data.array)

[[[-1.0 -2.0 279.8 269.5 260.9 265.0 263.5 -- 269.2]
  [272.7 -2.0 279.5 278.9 263.8 263.3 274.2 -- 279.5]
  [269.7 -2.0 273.4 274.2 -4.0 270.2 280.0 -- -5.0]
  [261.7 -2.0 270.8 260.3 265.6 279.4 276.9 -- 260.6]
  [264.2 -2.0 262.5 6.0 7.0 8.0 270.4 -- 275.3]
  [263.9 -2.0 272.1 3.0 4.0 5.0 260.0 -6.0 270.2]
  [273.8 -2.0 268.5 0.0 1.0 2.0 270.6 -- 270.6]
  [267.9 -2.0 279.8 260.3 261.2 275.3 271.2 -- 268.9]
  [270.9 -2.0 273.2 261.7 271.6 265.8 273.0 -- 266.4]
  [276.4 -2.0 276.3 266.1 -4.0 268.1 277.0 -- -5.0]]]


----

### Manipulating dimensions
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#manipulating-dimensions) 

In [55]:
    t

<Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K>

In [56]:
t2 = t.squeeze()
t2

<Field: air_temperature(grid_latitude(10), grid_longitude(9)) K>

In [57]:
print(t2.dimension_coordinates)

Constructs:
{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}


In [58]:
t3 = t2.insert_dimension(axis='domainaxis3', position=1)
t3

<Field: air_temperature(grid_latitude(10), time(1), grid_longitude(9)) K>

In [59]:
t3.transpose([2, 0, 1])

<Field: air_temperature(grid_longitude(9), grid_latitude(10), time(1)) K>

---

## Subspacing
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#subspacing)

In [60]:
print(q)

Field: specific_humidity (ncvar:q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(8)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [-75.0, ..., 75.0] degrees_north
                : longitude(8) = [22.5, ..., 337.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]



In [61]:
new = q[::-1, 0]
print(new)

Field: specific_humidity (ncvar:q)
----------------------------------
Data            : specific_humidity(latitude(5), longitude(1)) 1
Cell methods    : area: mean
Dimension coords: latitude(5) = [75.0, ..., -75.0] degrees_north
                : longitude(1) = [22.5] degrees_east
                : time(1) = [2019-01-01 00:00:00]



---

## Metadata constructs 2
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#metadata-constructs-2)

In [63]:
print(t.constructs.type('dimension_coordinate'))

Constructs:
{'dimensioncoordinate0': <DimensionCoordinate: atmosphere_hybrid_height_coordinate(1) >,
 'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>,
 'dimensioncoordinate3': <DimensionCoordinate: time(1) days since 2018-12-01 >}


In [65]:
print(t.constructs.type('cell_method', 'field_ancillary'))

Constructs:
{'cellmethod0': <CellMethod: domainaxis1: domainaxis2: mean where land (interval: 0.1 degrees)>,
 'cellmethod1': <CellMethod: domainaxis3: maximum>,
 'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}


In [66]:
print(t.constructs.property(standard_name='air_temperature standard_error'))

Constructs:
{'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}


In [67]:
print(t.constructs.property(standard_name='air_temperature standard_error',
                            unit='K'))

Constructs:
{'fieldancillary0': <FieldAncillary: air_temperature standard_error(10, 9) K>}


In [69]:
print(t.constructs.measure('area'))

Constructs:
{'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>}


In [70]:
 print(t.constructs.method('maximum'))

Constructs:
{'cellmethod1': <CellMethod: domainaxis3: maximum>}


----

In [72]:
print(t.constructs.type('auxiliary_coordinate').axis('domainaxis2'))

Constructs:
{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>,
 'auxiliarycoordinate1': <AuxiliaryCoordinate: longitude(9, 10) degrees_E>}


In [71]:
c = t.constructs.type('dimension_coordinate')
d = c.property(units='degrees')
print(d)

Constructs:
{'dimensioncoordinate1': <DimensionCoordinate: grid_latitude(10) degrees>,
 'dimensioncoordinate2': <DimensionCoordinate: grid_longitude(9) degrees>}


----

In [73]:
print(t.constructs.key('domainancillary2'))

Constructs:
{'domainancillary2': <DomainAncillary: surface_altitude(10, 9) m>}


In [74]:
print(t.constructs.key('cellmethod1'))

Constructs:
{'cellmethod1': <CellMethod: domainaxis3: maximum>}


In [75]:
print(t.constructs.key('auxiliarycoordinate2', 'cellmeasure0'))

Constructs:
{'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name=Grid latitude name(10) >,
 'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>}


----

In [76]:
print(t)

Field: air_temperature (ncvar:ta)
---------------------------------
Data            : air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(10), grid_longitude(9)) K
Cell methods    : grid_latitude(10): grid_longitude(9): mean where land (interval: 0.1 degrees) time(1): maximum
Field ancils    : air_temperature standard_error(grid_latitude(10), grid_longitude(9)) = [[0.76, ..., 0.32]] K
Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name=Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure:area(grid_longitude(9), grid_latitude(

In [77]:
print(t.constructs.name('latitude'))

Constructs:
{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>}


In [82]:
print(t.constructs.name('long_name=Grid latitude name'))

Constructs:
{'auxiliarycoordinate2': <AuxiliaryCoordinate: long_name=Grid latitude name(10) >}


In [83]:
print(t.constructs.name('measure:area'))

Constructs:
{'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>}


In [87]:
print(t.constructs.name('ncvar%b'))

Constructs:
{'domainancillary1': <DomainAncillary: ncvar%b(1) >}


----

In [89]:
print(t.constructs.type('cell_measure'))

Constructs:
{'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>}


In [90]:
print(t.cell_measures)

Constructs:
{'cellmeasure0': <CellMeasure: measure:area(9, 10) km2>}


----

In [91]:
c = t.constructs.name('radiation_wavelength')
c

<Constructs: >

In [92]:
print(c)

Constructs:
{}


In [93]:
len(c)

0

----

In [95]:
print(t.constructs('latitude'))

Constructs:
{'auxiliarycoordinate0': <AuxiliaryCoordinate: latitude(10, 9) degrees_N>}


----

### Accessing an individual metadata construct
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#accessing-an-individual-metadata-construct)

In [96]:
len(t.constructs.name('latitude'))

1

In [97]:
t.constructs.name('latitude').get()

<AuxiliaryCoordinate: latitude(10, 9) degrees_N>

----

In [102]:
c = t.constructs.property(units='km2').get()
c

<CellMeasure: measure:area(9, 10) km2>

In [103]:
c.name()

'measure:area'

In [104]:
t.names()

['air_temperature',
 'project=research',
 'units=K',
 'standard_name=air_temperature',
 'Conventions=CF-1.7',
 'ncvar%ta']

----

In [105]:
try:
    t.constructs.measure('volume').get()
except ValueError as error:
    print(error)

Can't get zero constructs


In [106]:
t.constructs.name('units=degrees')

<Constructs: dimension_coordinate(2)>

In [107]:
len(t.constructs.name('units:degrees'))

0

In [108]:
try:
    t.constructs.name('units:degrees').get()
except ValueError as error:
    print(error)

Can't get zero constructs


In [109]:
print(t.constructs.name('units:degrees').get(default=None))

None


----

In [110]:
t.get_construct(key='domainancillary2')

<DomainAncillary: surface_altitude(10, 9) m>

In [111]:
t.get_construct(key='cellmethod1')

<CellMethod: domainaxis3: maximum>

In [114]:
len(t.constructs.key('auxiliarycoordinate999'))

0

In [115]:
t.get_construct(key='auxiliarycoordinate999', default='NO CONSTRUCT')

'NO CONSTRUCT'

----

In [117]:
t.constructs.name('latitude').get_key()

'auxiliarycoordinate0'

----

In [118]:
t.constructs['auxiliarycoordinate0']

<AuxiliaryCoordinate: latitude(10, 9) degrees_N>

----

###  Metadata construct properties
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#metadata-construct-properties)

In [121]:
lon = q.constructs.name('longitude').get()   
lon

<DimensionCoordinate: longitude(8) degrees_east>

In [122]:
lon.set_property('long_name', 'Longitude')
lon.properties()

{'long_name': 'Longitude',
 'standard_name': 'longitude',
 'units': 'degrees_east'}

----

###  Metadata construct data
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#metadata-construct-data)

In [126]:
lon = q.constructs.name('longitude').get()
lon

<DimensionCoordinate: longitude(8) degrees_east>

In [127]:
lon.get_data()

<Data(8): [22.5, ..., 337.5] degrees_east>

In [128]:
lon.data[2] = 133.33
print(lon.data.array)

[  22.5    67.5   133.33  157.5   202.5   247.5   292.5   337.5 ]


----

In [130]:
key = t.constructs.name('latitude').get_key()
key

'auxiliarycoordinate0'

In [131]:
t.get_data_axes(key=key)

('domainaxis1', 'domainaxis2')

----

In [132]:
t.constructs.data_axes()

{'auxiliarycoordinate0': ('domainaxis1', 'domainaxis2'),
 'auxiliarycoordinate1': ('domainaxis2', 'domainaxis1'),
 'auxiliarycoordinate2': ('domainaxis1',),
 'cellmeasure0': ('domainaxis2', 'domainaxis1'),
 'dimensioncoordinate0': ('domainaxis0',),
 'dimensioncoordinate1': ('domainaxis1',),
 'dimensioncoordinate2': ('domainaxis2',),
 'dimensioncoordinate3': ('domainaxis3',),
 'domainancillary0': ('domainaxis0',),
 'domainancillary1': ('domainaxis0',),
 'domainancillary2': ('domainaxis1', 'domainaxis2'),
 'fieldancillary0': ('domainaxis1', 'domainaxis2')}

----

In [133]:
time = q.constructs('time').get()
time

<DimensionCoordinate: time(1) days since 2018-12-01 >

In [134]:
time.get_property('units'), time.get_property('calendar', default='standard')

('days since 2018-12-01', 'standard')

In [135]:
print(time.data.array)

[ 31.]


In [137]:
print(time.data.datetime_array)

[cftime.DatetimeGregorian(2019, 1, 1, 0, 0, 0, 0, 1, 1)]


----

## Domain
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#domain)

In [138]:
domain = t.get_domain()
domain

<Domain: {1, 1, 9, 10}>

In [139]:
print(domain)

Dimension coords: atmosphere_hybrid_height_coordinate(1) = [1.5]
                : grid_latitude(10) = [2.2, ..., -1.76] degrees
                : grid_longitude(9) = [-4.7, ..., -1.18] degrees
                : time(1) = [2019-01-01 00:00:00]
Auxiliary coords: latitude(grid_latitude(10), grid_longitude(9)) = [[53.941, ..., 50.225]] degrees_N
                : longitude(grid_longitude(9), grid_latitude(10)) = [[2.004, ..., 8.156]] degrees_E
                : long_name=Grid latitude name(grid_latitude(10)) = [--, ..., kappa]
Cell measures   : measure:area(grid_longitude(9), grid_latitude(10)) = [[2391.9657, ..., 2392.6009]] km2
Coord references: atmosphere_hybrid_height_coordinate
                : rotated_latitude_longitude
Domain ancils   : ncvar%a(atmosphere_hybrid_height_coordinate(1)) = [10.0] m
                : ncvar%b(atmosphere_hybrid_height_coordinate(1)) = [20.0]
                : surface_altitude(grid_latitude(10), grid_longitude(9)) = [[0.0, ..., 270.0]] m



In [140]:
description = domain.dump()

Domain Axis: atmosphere_hybrid_height_coordinate(1)
Domain Axis: grid_latitude(10)
Domain Axis: grid_longitude(9)
Domain Axis: time(1)

Dimension coordinate: atmosphere_hybrid_height_coordinate
    computed_standard_name = 'altitude'
    standard_name = 'atmosphere_hybrid_height_coordinate'
    Data(atmosphere_hybrid_height_coordinate(1)) = [1.5]
    Bounds:Data(atmosphere_hybrid_height_coordinate(1), 2) = [[1.0, 2.0]]

Dimension coordinate: grid_latitude
    standard_name = 'grid_latitude'
    units = 'degrees'
    Data(grid_latitude(10)) = [2.2, ..., -1.76] degrees
    Bounds:Data(grid_latitude(10), 2) = [[2.42, ..., -1.98]] degrees

Dimension coordinate: grid_longitude
    standard_name = 'grid_longitude'
    units = 'degrees'
    Data(grid_longitude(9)) = [-4.7, ..., -1.18] degrees
    Bounds:Data(grid_longitude(9), 2) = [[-4.92, ..., -0.96]] degrees

Dimension coordinate: time
    standard_name = 'time'
    units = 'days since 2018-12-01'
    Data(time(1)) = [2019-01-01 00:00:00]


----

In [145]:
domain = t.domain
domain.constructs('latitude').get().set_property('test', 'set by domain')
t.constructs('latitude').get().get_property('test')

'set by domain'

In [146]:
t.constructs('latitude').get().set_property('test', 'set by field')
domain.constructs('latitude').get().get_property('test')

'set by field'

In [151]:
domain.constructs('latitude').get().del_property('test')

AttributeError: 'AuxiliaryCoordinate' has no 'test' property

In [149]:
t.constructs('latitude').get().has_property('test')

AttributeError: 'Field' object has no attribute 'construct'

In [142]:
t.get_construct('latitude').get_property('test')

ValueError: Can't get zero constructs

In [143]:
t.get_construct('latitude').set_property('test', 'set by field')
domain.get_construct('latitude').get_property('test')

ValueError: Can't get zero constructs

In [144]:
domain.get_construct('latitude').del_property('test')

ValueError: Can't get zero constructs

In [ ]:
t.get_construct('latitude').has_property('test')

----

## Domain axes
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#domain-axes)

In [ ]:
q.domain_axes

In [ ]:
d = q.get_construct(key='domainaxis1')
d.get_size()

----

## Coordinates
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#coordinates)

In [ ]:
t.coordinates

----

In [ ]:
lon = t.get_construct('grid_longitude')
bounds = lon.get_bounds()
bounds

In [ ]:
bounds.data

In [ ]:
print(bounds.data.array)

----

In [ ]:
bounds.inherited_properties()

In [ ]:
bounds.properties()

----

### Domain ancillaries
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#domain-ancillaries)

In [ ]:
a = t.get_construct(key='domainancillary0')
print(a.data.array)

In [ ]:
bounds = a.get_bounds()
print(bounds.data.array)

----

## Coordinate systems
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#coordinate-systems)

In [ ]:
crs = t.get_construct('atmosphere_hybrid_height_coordinate',
                      construct='coordinate_reference')
crs

In [ ]:
crs.dump()

In [ ]:
crs.coordinates()

----

In [ ]:
crs.get_datum()

In [ ]:
crs.datum.parameters()

----

In [ ]:
crs.get_coordinate_conversion()

In [ ]:
crs.coordinate_conversion.parameters()

In [ ]:
crs.coordinate_conversion.domain_ancillaries()

----

## Cell methods
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#cell-methods)

In [ ]:
print(t.cell_methods)

----

In [ ]:
t.cell_methods.ordered()

----

In [ ]:
cm = t.get_construct(key='cellmethod0')
cm

In [ ]:
cm.get_axes()

In [ ]:
cm.get_method()

In [ ]:
cm.properties()

In [ ]:
cm.get_property('where')

---

## Field construct creation
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#field-construct-creation)

### Manual creation
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#manual-creation)

In [ ]:
p = cfdm.Field(properties={'standard_name': 'precipitation_flux'})
p

In [ ]:
dc = cfdm.DimensionCoordinate(properties={'long_name': 'Longitude'},
                              data=cfdm.Data([0, 1, 2.]))
dc

In [ ]:
fa = cfdm.FieldAncillary(
           properties={'standard_name': 'precipitation_flux status_flag'},
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

---

In [ ]:
p = cfdm.Field()
p

In [ ]:
p.set_property('standard_name', 'precipitation_flux')
p

In [ ]:
dc = cfdm.DimensionCoordinate()
dc

In [ ]:
dc.set_property('long_name', 'Longitude')
dc.set_data(cfdm.Data([1, 2, 3.]))
dc

In [ ]:
fa = cfdm.FieldAncillary(
           data=cfdm.Data(numpy.array([0, 0, 2], dtype='int8')))
fa

In [ ]:
fa.set_property('standard_name', 'precipitation_flux status_flag')
fa

---

In [ ]:
longitude_axis = p.set_construct(cfdm.DomainAxis(3))
longitude_axis

In [ ]:
key = p.set_construct(dc, axes=[longitude_axis])
key

In [ ]:
cm = cfdm.CellMethod(axes=[longitude_axis],
                     properties={'method': 'minimum'})
p.set_construct(cm)

---

In [ ]:
import numpy
import cfdm

# Initialise the field construct with properties
Q = cfdm.Field(properties={'project': 'research',
                           'standard_name': 'specific_humidity',
                           'units': '1'})

# Create the domain axis constructs
domain_axisT = cfdm.DomainAxis(1)
domain_axisY = cfdm.DomainAxis(5)
domain_axisX = cfdm.DomainAxis(8)

# Insert the domain axis constructs into the field. The
# set_construct method returns the domain axis construct key that
# will be used later to specify which domain axis corresponds to
# which dimension coordinate construct.
axisT = Q.set_construct(domain_axisT)
axisY = Q.set_construct(domain_axisY)
axisX = Q.set_construct(domain_axisX)

# Create and insert the field construct data
data = cfdm.Data(numpy.arange(40.).reshape(5, 8))
Q.set_data(data, axes=[axisY, axisX])

# Create the cell method constructs
cell_method1 = cfdm.CellMethod(axes='area', method='mean')

cell_method2 = cfdm.CellMethod()
cell_method2.set_axes(axisT)
cell_method2.set_method('maximum')

# Insert the cell method constructs into the field in the same
# order that their methods were applied to the data
Q.set_construct(cell_method1)
Q.set_construct(cell_method2)

# Create a "time" dimension coordinate construct, with coordinate
# bounds
dimT = cfdm.DimensionCoordinate(
                            properties={'standard_name': 'time',
                                        'units': 'days since 2018-12-01'},
                            data=cfdm.Data([15.5]),
                            bounds=cfdm.Bounds(data=cfdm.Data([[0,31.]])))

# Create a "longitude" dimension coordinate construct, without
# coordinate bounds
dimX = cfdm.DimensionCoordinate(data=cfdm.Data(numpy.arange(8.)))
dimX.set_properties({'standard_name': 'longitude',
                     'units': 'degrees_east'})

# Create a "longitude" dimension coordinate construct
dimY = cfdm.DimensionCoordinate(properties={'standard_name': 'latitude',
                                            'units': 'degrees_north'})
array = numpy.arange(5.)
dimY.set_data(cfdm.Data(array))

# Create and insert the latitude coordinate bounds
bounds_array = numpy.empty((5, 2))
bounds_array[:, 0] = array - 0.5
bounds_array[:, 1] = array + 0.5
bounds = cfdm.Bounds(data=cfdm.Data(bounds_array))
dimY.set_bounds(bounds)

# Insert the dimension coordinate constructs into the field,
# specifying to # which domain axis each one corresponds
Q.set_construct(dimT, axes=axisT)
Q.set_construct(dimY, axes=axisY)
Q.set_construct(dimX, axes=axisX)

---

In [ ]:
Q.dump()

----

In [ ]:
Q.nc_set_variable('q')

domain_axisT.nc_set_dimension('time')
domain_axisY.nc_set_dimension('lat')
domain_axisX.nc_set_dimension('lon')

dimT.nc_set_variable('time')
dimY.nc_set_variable('lat')
dimX.nc_set_variable('lon')

----

In [ ]:
import numpy
import cfdm

# Initialize the field construct
tas = cfdm.Field(
    properties={'project': 'research',
                'standard_name': 'air_temperature',
                'units': 'K'})

# Create and set domain axis constructs
axis_T = tas.set_construct(cfdm.DomainAxis(1))
axis_Z = tas.set_construct(cfdm.DomainAxis(1))
axis_Y = tas.set_construct(cfdm.DomainAxis(10))
axis_X = tas.set_construct(cfdm.DomainAxis(9))

# Set the field construct data
tas.set_data(cfdm.Data(numpy.arange(90.).reshape(10, 9)),
             axes=[axis_Y, axis_X])

# Create and set the cell method constructs
cell_method1 = cfdm.CellMethod(
          axes=[axis_Y, axis_X],
          method='mean',
          properties={'where': 'land',
                      'interval': [cfdm.Data(0.1, units='degrees')]})

cell_method2 = cfdm.CellMethod(axes=axis_T, method='maximum')

tas.set_construct(cell_method1)
tas.set_construct(cell_method2)

# Create and set the field ancillary constructs
field_ancillary = cfdm.FieldAncillary(
             properties={'standard_name': 'air_temperature standard_error',
                          'units': 'K'},
             data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

tas.set_construct(field_ancillary, axes=[axis_Y, axis_X])

# Create and set the dimension coordinate constructs
dimension_coordinate_T = cfdm.DimensionCoordinate(
                           properties={'standard_name': 'time',
                                       'units': 'days since 2018-12-01'},
                           data=cfdm.Data([15.5]),
                           bounds=cfdm.Bounds(data=cfdm.Data([[0., 31]])))

dimension_coordinate_Z = cfdm.DimensionCoordinate(
        properties={'computed_standard_name': 'altitude',
                    'standard_name': 'atmosphere_hybrid_height_coordinate'},
        data = cfdm.Data([1.5]),
        bounds=cfdm.Bounds(data=cfdm.Data([[1.0, 2.0]])))

dimension_coordinate_Y = cfdm.DimensionCoordinate(
        properties={'standard_name': 'grid_latitude',
                    'units': 'degrees'},
        data=cfdm.Data(numpy.arange(10.)),
        bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(20).reshape(10, 2))))

dimension_coordinate_X = cfdm.DimensionCoordinate(
        properties={'standard_name': 'grid_longitude',
                    'units': 'degrees'},
    data=cfdm.Data(numpy.arange(9.)),
    bounds=cfdm.Bounds(data=cfdm.Data(numpy.arange(18).reshape(9, 2))))

dim_T = tas.set_construct(dimension_coordinate_T, axes=axis_T)
dim_Z = tas.set_construct(dimension_coordinate_Z, axes=axis_Z)
dim_Y = tas.set_construct(dimension_coordinate_Y, axes=axis_Y)
dim_X = tas.set_construct(dimension_coordinate_X, axes=axis_X)

# Create and set the auxiliary coordinate constructs
auxiliary_coordinate_lat = cfdm.AuxiliaryCoordinate(
                      properties={'standard_name': 'latitude',
                                  'units': 'degrees_north'},
                      data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

auxiliary_coordinate_lon = cfdm.AuxiliaryCoordinate(
                  properties={'standard_name': 'longitude',
                              'units': 'degrees_east'},
                  data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

array = numpy.ma.array(list('abcdefghij'))
array[0] = numpy.ma.masked
auxiliary_coordinate_name = cfdm.AuxiliaryCoordinate(
                       properties={'long_name': 'Grid latitude name'},
                       data=cfdm.Data(array))

aux_LAT  = tas.set_construct(auxiliary_coordinate_lat, axes=[axis_Y, axis_X])
aux_LON  = tas.set_construct(auxiliary_coordinate_lon, axes=[axis_X, axis_Y])
aux_NAME = tas.set_construct(auxiliary_coordinate_name, axes=[axis_Y])

# Create and set domain ancillary constructs
domain_ancillary_a = cfdm.DomainAncillary(
                   properties={'units': 'm'},
                   data=cfdm.Data([10.]),
                   bounds=cfdm.Bounds(data=cfdm.Data([[5., 15.]])))

domain_ancillary_b = cfdm.DomainAncillary(
                       properties={'units': '1'},
                       data=cfdm.Data([20.]),
                       bounds=cfdm.Bounds(data=cfdm.Data([[14, 26.]])))

domain_ancillary_orog = cfdm.DomainAncillary(
                          properties={'standard_name': 'surface_altitude',
                                     'units': 'm'},
                          data=cfdm.Data(numpy.arange(90.).reshape(10, 9)))

domain_anc_A    = tas.set_construct(domain_ancillary_a, axes=axis_Z)
domain_anc_B    = tas.set_construct(domain_ancillary_b, axes=axis_Z)
domain_anc_OROG = tas.set_construct(domain_ancillary_orog,
                                    axes=[axis_Y, axis_X])

# Create the datum for the coordinate reference constructs
datum = cfdm.Datum(parameters={'earth_radius': 6371007.})

# Create the coordinate conversion for the horizontal coordinate
# reference construct
coordinate_conversion_h = cfdm.CoordinateConversion(
              parameters={'grid_mapping_name': 'rotated_latitude_longitude',
                          'grid_north_pole_latitude': 38.0,
                          'grid_north_pole_longitude': 190.0})

# Create the coordinate conversion for the vertical coordinate
# reference construct
coordinate_conversion_v = cfdm.CoordinateConversion(
         parameters={'standard_name': 'atmosphere_hybrid_height_coordinate',
                     'computed_standard_name': 'altitude'},
         domain_ancillaries={'a': domain_anc_A,
                             'b': domain_anc_B,
                             'orog': domain_anc_OROG})

# Create the vertical coordinate reference construct
horizontal_crs = cfdm.CoordinateReference(
                   datum=datum,
                   coordinate_conversion=coordinate_conversion_h,
                   coordinates=[dim_X,
                                dim_Y,
                                aux_LAT,
                                aux_LON])

# Create the vertical coordinate reference construct
vertical_crs = cfdm.CoordinateReference(
                 datum=datum,
                 coordinate_conversion=coordinate_conversion_v,
                 coordinates=[dim_Z])

# Set the coordinate reference constructs
tas.set_construct(horizontal_crs)
tas.set_construct(vertical_crs)

# Create and set the cell measure constructs
cell_measure = cfdm.CellMeasure(measure='area',
                 properties={'units': 'km2'},
                 data=cfdm.Data(numpy.arange(90.).reshape(9, 10)))

tas.set_construct(cell_measure, axes=[axis_X, axis_Y])

----

In [ ]:
print(tas)

---

### Creating data from an array on disk
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#creating-data-from-an-array-on-disk)

In [ ]:
import netCDF4
nc = netCDF4.Dataset('file.nc', 'r')
v = nc.variables['ta']

In [ ]:
netcdf_array = cfdm.NetCDFArray(filename='file.nc', ncvar='ta',
                                dtype=v.dtype, ndim=v.ndim,
                                shape=v.shape, size=v.size)
data_disk = cfdm.Data(netcdf_array)

----

In [ ]:
numpy_array = v[...]
data_memory = cfdm.Data(numpy_array)
data_disk.equals(data_memory)

----

### Creation by conversion
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#creation-by-conversion)

In [ ]:
orog = tas.convert('surface_altitude')
print(orog)

In [ ]:
orog1 = tas.convert('surface_altitude', full_domain=False)
print(orog1)

---

### Creation by reading
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#creation-by-reading)

In [ ]:
cfdm.write(tas, 'tas.nc')
f = cfdm.read('tas.nc')
f

----

In [ ]:
fields = cfdm.read('tas.nc', extra='domain_ancillary')
fields

In [ ]:
fields = cfdm.read('tas.nc', extra='domain_ancillary')
orog_from_file = fields[3]

In [ ]:
print(orog_from_file)

----

## Copying
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#copying)

In [ ]:
u = t.copy()
u.data[0, 0, 0] = -1e30
u.data[0, 0, 0]

In [ ]:
t.data[0, 0, 0]

In [ ]:
u.del_construct('grid_latitude')

In [ ]:
u.constructs('grid_latitude')


In [ ]:
t.constructs('grid_latitude')

----

In [ ]:
import copy
u = copy.deepcopy(t)

----

In [ ]:
orog = t.get_construct('surface_altitude').copy()

----

## Equality
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#equality)

In [ ]:
t.equals(t)

In [ ]:
t.equals(t.copy())

In [ ]:
t.equals(t[...])

In [ ]:
t.equals(q)

In [ ]:
t.equals(q, verbose=True)

----

In [ ]:
cfdm.ATOL()

In [ ]:
cfdm.RTOL()

In [ ]:
original = cfdm.RTOL(0.00001)
cfdm.RTOL()

In [ ]:
cfdm.RTOL(original)

In [ ]:
cfdm.RTOL()

----

In [ ]:
orog = t.get_construct('surface_altitude')
orog.equals(orog.copy())

----

## NetCDF interface
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#netcdf-interface)

In [ ]:
print(t.constructs(ncvar='b'))

In [ ]:
t.get_construct('ncvar%x')

In [ ]:
t.get_construct(ncdim='x')

---

In [ ]:
q.nc_get_variable()

In [ ]:
q.nc_global_attributes()

In [ ]:
q.nc_unlimited_dimensions()

In [ ]:
q.nc_set_variable('humidity')
q.nc_get_variable()

In [ ]:
q.get_construct('latitude').nc_get_variable()

---

## Writing to disk
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#writing-to-disk)

In [ ]:
print(q)

In [ ]:
cfdm.write(q, 'q_file.nc')

In [ ]:
!ncdump -h q_file.nc

---

In [ ]:
x

In [ ]:
cfdm.write(x, 'new_file.nc')

### Scalar coordinate variables
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#scalar-coordinate-variables)

In [ ]:
print(q)

In [ ]:
q.get_construct_data_axes('time')

In [ ]:
q2 = q.insert_dimension(axis='domainaxis2')
q2

In [ ]:
cfdm.write(q2, 'q2_file.nc')

In [ ]:
!ncdump -h q2_file.nc

---

## External variables
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#external-variables)

In [ ]:
!ncdump -h parent.nc

In [ ]:
!ncdump -h external.nc 

In [ ]:
u = cfdm.read(DIRECTORY+'/parent.nc')[0]
print(u)

In [ ]:
area = u.get_construct('measure:area')
area

In [ ]:
area.nc_external()

In [ ]:
area.nc_get_variable()

In [ ]:
area.properties()

In [ ]:
area.has_data()

---

In [ ]:
g = cfdm.read(DIRECTORY+'/parent.nc', external=DIRECTORY+'/external.nc')[0]
print(g)

In [ ]:
area = g.get_construct('cell_area')
area

In [ ]:
area.nc_external()

In [ ]:
area.nc_get_variable()

In [ ]:
area.properties()

In [ ]:
area.data

---

In [ ]:
area.nc_external(True)

In [ ]:
cfdm.write(g, 'new_parent.nc', external='new_external.nc')

---

## Compression
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#compression)

---

## Discrete sampling geometries
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#discrete-sampling-geometries)

In [ ]:
!ncdump -h contiguous.nc

---

In [ ]:
h = cfdm.read(DIRECTORY+'/contiguous.nc')[0]
print(h)

In [ ]:
print(h.data.array)

----

In [ ]:
h.data.get_compression_type()

In [ ]:
print(h.data.compressed_array)

In [ ]:
count_variable = h.data.get_count_variable()
count_variable

In [ ]:
print(count_variable.data.array)

---

In [ ]:
station2 = h[1]
station2

In [ ]:
print(station2.data.array)

---

In [ ]:
h.data.get_compression_type()

In [ ]:
h.data[1, 2] = -9
print(h.data.array)

In [ ]:
h.data.get_compression_type()

---

In [ ]:
import numpy
import cfdm

# Define the ragged array values
ragged_array = numpy.array([280, 282.5, 281, 279, 278, 279.5],
                           dtype='float32')

# Define the count array values
count_array = [2, 4]

# Create the count variable
count_variable = cfdm.Count(data=cfdm.Data(count_array))
count_variable.set_property('long_name', 'number of obs for this timeseries')

# Create the contiguous ragged array object
array = cfdm.RaggedContiguousArray(
                 compressed_array=cfdm.NumpyArray(ragged_array),
                 shape=(2, 4), size=8, ndim=2,
                 count_variable=count_variable)

# Create the field construct with the domain axes and the ragged
# array
T = cfdm.Field()
T.set_properties({'standard_name': 'air_temperature',
                  'units': 'K',
                  'featureType': 'timeSeries'})

# Create the domain axis constructs for the uncompressed array
X = T.set_construct(cfdm.DomainAxis(4))
Y = T.set_construct(cfdm.DomainAxis(2))

# Set the data for the field
T.set_data(cfdm.Data(array), axes=[Y, X])

---

In [ ]:
T

In [ ]:
print(T.data.array)

In [ ]:
T.data.get_compression_type()

In [ ]:
print(T.data.compressed_array)

In [ ]:
count_variable = T.data.get_count_variable()
count_variable

In [ ]:
print(count_variable.data.array)

In [ ]:
cfdm.write(T, 'T_contiguous.nc')

----

In [ ]:
!ncdump T_contiguous.nc

---

## Gathering
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html#gathering)

In [ ]:
p = cfdm.read(DIRECTORY+'/gathered.nc')[0]
print(p)

In [ ]:
print(p.data.array)

----

In [ ]:
p.data.get_compression_type()

In [ ]:
print(p.data.compressed_array)

In [ ]:
list_variable = p.data.get_list_variable()
list_variable

In [ ]:
print(list_variable.data.array)

---

In [ ]:
p[0]

In [ ]:
p[1, :, 3:5]

---

In [ ]:
p.data.get_compression_type()

In [ ]:
p.data[1] = -9

In [ ]:
p.data.get_compression_type()

---

In [ ]:
import numpy
import cfdm

# Define the gathered values
gathered_array = numpy.array([[2, 1, 3], [4, 0, 5]],
                             dtype='float32')

# Define the list array values
list_array = [1, 4, 5]

# Create the list variable
list_variable = cfdm.List(data=cfdm.Data(list_array))

# Create the gathered array object
array = cfdm.GatheredArray(
                 compressed_array=cfdm.NumpyArray(gathered_array),
                 compressed_dimension=1,
                 shape=(2, 3, 2), size=12, ndim=3,
                 list_variable=list_variable)

# Create the field construct with the domain axes and the gathered
# array
P = cfdm.Field(properties={'standard_name': 'precipitation_flux',
                           'units': 'kg m-2 s-1'})

# Create the domain axis constructs for the uncompressed array
T = P.set_construct(cfdm.DomainAxis(2))
Y = P.set_construct(cfdm.DomainAxis(3))
X = P.set_construct(cfdm.DomainAxis(2))

# Set the data for the field
P.set_data(cfdm.Data(array), axes=[T, Y, X])

---

In [ ]:
P

In [ ]:
print(P.data.array)

In [ ]:
P.data.get_compression_type()

In [ ]:
print(P.data.compressed_array)

In [ ]:
list_variable = P.data.get_list_variable()
list_variable 

In [ ]:
print(list_variable.data.array)

In [ ]:
cfdm.write(P, 'P_gathered.nc')

----

In [ ]:
!ncdump P_gathered.nc

---
[**Back to top**](#cfdm-tutorial-notebook)  
[**Go to tutorial**](https://ncas-cms.github.io/cfdm/tutorial.html)  